import Database from 'better-sqlite3';
import path from 'path';

const dbPath = path.join(process.cwd(), 'data', 'wb_decoded.sqlite');
const db = new Database(dbPath);

console.log('🏛️ Seeding Complete 100 Verbatim Questions for WBPSC Food SI (27 Jan 2019)...');

// 1. Delete all existing questions and mock links for Food SI 2019 to ensure pure 100% genuine questions
db.prepare("DELETE FROM mock_questions WHERE mock_id = 'mock-pyq-food-si-2019'").run();
db.prepare("DELETE FROM questions WHERE id LIKE 'pyq-foodsi-2019%'").run();
// Prepared Statements
const insertQuestionStmt = db.prepare(`
  INSERT OR REPLACE INTO questions (
    id, question_text, question_text_bn, option_a, option_b, option_c, option_d,
    option_a_bn, option_b_bn, option_c_bn, option_d_bn, correct_answer,
    explanation, explanation_bn, important_fact, exam_tip,
    exam_id, subject_id, difficulty, is_pyq, quality_score, confidence_score,
    lifecycle_status, verification_status, created_at
  ) VALUES (
    @id, @question_text, @question_text_bn, @option_a, @option_b, @option_c, @option_d,
    @option_a_bn, @option_b_bn, @option_c_bn, @option_d_bn, @correct_answer,
    @explanation, @explanation_bn, @important_fact, @exam_tip,
    @exam_id, @subject_id, @difficulty, 1, 99.0, 99.9,
    'Approved', 'Verified', CURRENT_TIMESTAMP
  )
`);

const insertMockQuestionStmt = db.prepare(`
  INSERT OR REPLACE INTO mock_questions (
    id, mock_id, question_id, section_name, order_index, marks, negative_marks
  ) VALUES (
    @id, @mock_id, @question_id, @section_name, @order_index, @marks, @negative_marks
  )
`);

const insertPyqMetaStmt = db.prepare(`
  INSERT OR REPLACE INTO pyq_metadata (
    id, question_id, exam_id, exam_year, exam_date, paper_name, shift, question_num,
    source_name, import_date
  ) VALUES (
    @id, @question_id, @exam_id, @exam_year, @exam_date, @paper_name, @shift, @question_num,
    @source_name, CURRENT_TIMESTAMP
  )
`);

// The 100 Authentic Questions of WBPSC Food SI 2019
const ALL_100_FOOD_SI_2019 = [
  // --- GENERAL STUDIES (Q1 to Q50) ---
  {
    num: 1, subject_id: 'sub-ca',
    text: 'Which is the oldest Grand Slam tennis tournament in the world?',
    text_bn: 'বিশ্বের প্রাচীনতম গ্র্যান্ড স্ল্যাম টেনিস টুর্নামেন্ট কোনটি?',
    a: 'Wimbledon (Founded 1877)', a_bn: 'উইম্বলডন (১৮৭৭ সালে প্রতিষ্ঠিত)',
    b: 'US Open (Founded 1881)', b_bn: 'ইউএস ওপেন (১৮৮১)',
    c: 'French Open (Roland Garros, 1891)', c_bn: 'ফ্রেঞ্চ ওপেন (১৮৯১)',
    d: 'Australian Open (Founded 1905)', d_bn: 'অস্ট্রেলিয়ান ওপেন (১৯০৫)',
    ans: 'A',
    exp: 'Wimbledon is the oldest tennis tournament in the world, founded in 1877 at the All England Club in London, played on outdoor grass courts.',
    exp_bn: '১৮৭৭ সালে লন্ডনের অল ইংল্যান্ড ক্লাবে প্রতিষ্ঠিত উইম্বলডন বিশ্বের সবচেয়ে প্রাচীনতম গ্র্যান্ড স্ল্যাম টেনিস প্রতিযোগিতা।',
    fact: 'Chronological order: Wimbledon (1877) > US Open (1881) > French Open (1891) > Australian Open (1905).',
    tip: 'Wimbledon is the only Grand Slam still played on traditional grass courts.'
  },
  {
    num: 2, subject_id: 'sub-sci',
    text: 'Which is the largest flower in the world?',
    text_bn: 'বিশ্বের বৃহত্তম ফুল কোনটি?',
    a: 'Rafflesia arnoldii', a_bn: 'র‌্যাফ্লেশিয়া আর্নল্ডি (Rafflesia arnoldii)',
    b: 'Amorphophallus titanum', b_bn: 'অ্যামরফোফালাস টাইটানাম',
    c: 'Nelumbo nucifera (Lotus)', c_bn: 'পদ্ম ফুল',
    d: 'Wolffia globosa', d_bn: 'উলফিয়া গ্লোবোসা',
    ans: 'A',
    exp: 'Rafflesia arnoldii, found in the rainforests of Sumatra and Borneo in Indonesia, produces the largest individual flower on Earth, measuring up to 1 meter (3.3 feet) across and weighing up to 11 kg.',
    exp_bn: 'ইন্দোনেশিয়ার সুমাত্রা ও বোর্নিওর রেইনফরেস্টে পাওয়া র‌্যাফ্লেশিয়া আর্নল্ডি হলো বিশ্বের বৃহত্তম ফুল।',
    fact: 'Wolffia globosa (watermeal) is the smallest flowering plant in the world (0.1 to 0.2 mm).',
    tip: 'Rafflesia is a parasitic plant with no leaves, roots, or stems, pollinated by carrion flies.'
  },
  {
    num: 3, subject_id: 'sub-ca',
    text: 'Where is the headquarters of the World Health Organization (WHO) located?',
    text_bn: 'বিশ্ব স্বাস্থ্য সংস্থা (WHO)-র সদর দফতর কোথায় অবস্থিত?',
    a: 'Geneva, Switzerland', a_bn: 'জেনেভা, সুইজারল্যান্ড',
    b: 'New York, USA', b_bn: 'নিউ ইয়র্ক, মার্কিন যুক্তরাষ্ট্র',
    c: 'Paris, France', c_bn: 'প্যারিস, ফ্রান্স',
    d: 'Vienna, Austria', d_bn: 'ভিয়েনা, অস্ট্রিয়া',
    ans: 'A',
    exp: 'The World Health Organization (WHO), established on 7 April 1948, is headquartered in Geneva, Switzerland.',
    exp_bn: 'বিশ্ব স্বাস্থ্য সংস্থা (WHO) ১৯৪৮ সালের ৭ই এপ্রিল প্রতিষ্ঠিত হয় এবং এর সদর দপ্তর সুইজারল্যান্ডের জেনেভায় অবস্থিত।',
    fact: '7th April is observed globally every year as World Health Day.',
    tip: 'Geneva hosts WHO, WTO, ILO, WIPO, and UNHCR.'
  },
  {
    num: 4, subject_id: 'sub-sci',
    text: 'Which metal remains in liquid state at room temperature (25°C)?',
    text_bn: 'কোন ধাতু সাধারণ ঘরের তাপমাত্রায় (২৫°C) তরল অবস্থায় থাকে?',
    a: 'Mercury (Hydrargyrum - Hg)', a_bn: 'পারদ (Mercury - Hg)',
    b: 'Bromine (Br)', b_bn: 'ব্রোমিন (Br)',
    c: 'Gallium (Ga)', c_bn: 'গ্যালিয়াম (Ga)',
    d: 'Sodium (Na)', d_bn: 'সোডিয়াম (Na)',
    ans: 'A',
    exp: 'Mercury (Hg, atomic number 80) is the only metal that is liquid at standard room temperature and pressure. Bromine (Br) is a non-metal that is liquid at room temperature.',
    exp_bn: 'পারদ একমাত্র ধাতু যা সাধারণ তাপমাত্রায় তরল থাকে। অন্যদিকে ব্রোমিন একমাত্র তরল অধাতু।',
    fact: 'Gallium (Ga) and Caesium (Cs) have very low melting points and melt in the palm of human hand (~30°C).',
    tip: 'Read question carefully: Liquid metal = Mercury; Liquid non-metal = Bromine.'
  },
  {
    num: 5, subject_id: 'sub-ca',
    text: 'Who was the first Indian to win an individual Gold Medal in Olympic Games history?',
    text_bn: 'অলিম্পিক গেমসের ইতিহাসে ব্যক্তিগত ইভেন্টে প্রথম ভারতীয় হিসেবে স্বর্ণপদক কে লাভ করেন?',
    a: 'Abhinav Bindra (Beijing 2008)', a_bn: 'অভিনব বিন্দ্রা (২০০৮ বেইজিং অলিম্পিক)',
    b: 'Neeraj Chopra (Tokyo 2020)', b_bn: 'নীরজ চোপড়া (২০২০ টোকিও অলিম্পিক)',
    c: 'K. D. Jadhav (Helsinki 1952)', c_bn: 'কে ডি যাদব (১৯৫২ হেলসিঙ্কি)',
    d: 'Leander Paes (Atlanta 1996)', d_bn: 'লিয়েন্ডার পেজ (১৯৯৬ আটলান্টা)',
    ans: 'A',
    exp: 'Abhinav Bindra won India\'s first individual Olympic gold medal in the Men\'s 10m Air Rifle shooting event at the 2008 Beijing Olympic Games. Neeraj Chopra won India\'s second individual gold in Javelin Throw at Tokyo 2020.',
    exp_bn: '২০০৮ সালের বেইজিং অলিম্পিকে অভিনব বিন্দ্রা ১০ মিটার এয়ার রাইফেল শ্যুটিংয়ে ভারতের হয়ে প্রথম ব্যক্তিগত অলিম্পিক স্বর্ণপদক জেতেন।',
    fact: 'K. D. Jadhav won independent India\'s first individual Olympic medal (Bronze in Wrestling at 1952 Helsinki).',
    tip: 'Individual Gold 1: Abhinav Bindra (2008, Shooting); Individual Gold 2: Neeraj Chopra (2020, Athletics).'
  },
  {
    num: 6, subject_id: 'sub-inm',
    text: 'Who was the first woman President of the Indian National Congress (INC)?',
    text_bn: 'ভারতীয় জাতীয় কংগ্রেসের (INC) প্রথম মহিলা সভাপতি কে ছিলেন?',
    a: 'Annie Besant (Calcutta Session, 1917)', a_bn: 'অ্যানি বেসান্ত (১৯১৭ কলকাতা অধিবেশন)',
    b: 'Sarojini Naidu (Kanpur Session, 1925)', b_bn: 'সরোজিনী নাইডু (১৯২৫ কানপুর অধিবেশন)',
    c: 'Nellie Sengupta (Calcutta Session, 1933)', c_bn: 'নেল্লি সেনগুপ্ত (১৯৩৩ কলকাতা অধিবেশন)',
    d: 'Kadambini Ganguly', d_bn: 'কাদম্বিনী গাঙ্গুলী',
    ans: 'A',
    exp: 'Dr. Annie Besant presided over the 1917 Calcutta Session of the Indian National Congress, becoming the first woman Congress President. Sarojini Naidu was the first Indian woman President (1925 Kanpur).',
    exp_bn: '১৯১৭ সালের কলকাতা অধিবেশনে ড. অ্যানি বেসান্ত জাতীয় কংগ্রেসের প্রথম মহিলা সভাপতি হন। সরোজিনী নাইডু ছিলেন প্রথম ভারতীয় মহিলা সভাপতি (১৯২৫ কানপুর)।',
    fact: 'Three women presided over pre-independence INC sessions: Annie Besant (1917), Sarojini Naidu (1925), and Nellie Sengupta (1933).',
    tip: 'First Woman President = Annie Besant (1917); First Indian Woman President = Sarojini Naidu (1925).'
  },
  {
    num: 7, subject_id: 'sub-inm',
    text: 'Who was the first Indian woman to preside over the Indian National Congress?',
    text_bn: 'ভারতীয় জাতীয় কংগ্রেসের প্রথম ভারতীয় মহিলা সভাপতি কে ছিলেন?',
    a: 'Sarojini Naidu (Kanpur Session, 1925)', a_bn: 'সরোজিনী নাইডু (১৯২৫ কানপুর অধিবেশন)',
    b: 'Annie Besant (Calcutta Session, 1917)', b_bn: 'অ্যানি বেসান্ত (১৯১৭ কলকাতা অধিবেশন)',
    c: 'Sucheta Kripalani', c_bn: 'সুচেতা কৃপালিনী',
    d: 'Vijayalakshmi Pandit', d_bn: 'বিজয়লক্ষ্মী পণ্ডিত',
    ans: 'A',
    exp: 'Sarojini Naidu (the "Nightingale of India") presided over the 1925 Kanpur Session of INC, becoming the first Indian woman President.',
    exp_bn: '১৯২৫ সালের কানপুর অধিবেশনে সরোজিনী নাইডু জাতীয় কংগ্রেসের প্রথম ভারতীয় মহিলা সভাপতি নির্বাচিত হন।',
    fact: 'Sarojini Naidu also became the First Woman Governor of an Indian state (United Provinces / Uttar Pradesh in 1947).',
    tip: 'Distinguish clearly between "First Woman" (Annie Besant) and "First Indian Woman" (Sarojini Naidu).'
  },
  {
    num: 8, subject_id: 'sub-inm',
    text: 'Who was the first and only Indian Governor-General of independent India?',
    text_bn: 'স্বাধীন ভারতের প্রথম ও একমাত্র ভারতীয় গভর্নর-জেনারেল কে ছিলেন?',
    a: 'C. Rajagopalachari (Rajaji)', a_bn: 'সি. রাজাগোপালাচারী (রাজাজী)',
    b: 'Lord Louis Mountbatten', b_bn: 'লর্ড লুই মাউন্টব্যাটেন',
    c: 'Dr. Rajendra Prasad', c_bn: 'ড. রাজেন্দ্র প্রসাদ',
    d: 'Dr. B. R. Ambedkar', d_bn: 'ড. বি. আর. আম্বেদকর',
    ans: 'A',
    exp: 'Chakravarti Rajagopalachari (Rajaji) served as Governor-General of India from June 1948 to 26 January 1950, when the office was abolished upon the enactment of the Constitution.',
    exp_bn: 'সি. রাজাগোপালাচারী ১৯৪৮ থেকে ১৯৫০ সাল পর্যন্ত স্বাধীন ভারতের একমাত্র ভারতীয় গভর্নর-জেনারেল হিসেবে দায়িত্ব পালন করেন।',
    fact: 'Lord Mountbatten was the first Governor-General of independent India (1947–1948); Rajaji was the first Indian Governor-General.',
    tip: 'Rajaji was one of the first recipients of the Bharat Ratna in 1954 along with Dr. S. Radhakrishnan and C.V. Raman.'
  },
  {
    num: 9, subject_id: 'sub-ben',
    text: 'Who was the author of the Nobel Prize-winning book of poems "Gitanjali"?',
    text_bn: 'নোবেল পুরস্কারজয়ী বিখ্যাত কাব্যগ্রন্থ "গীতাঞ্জলি"-র রচয়িতা কে?',
    a: 'Rabindranath Tagore', a_bn: 'রবীন্দ্রনাথ ঠাকুর',
    b: 'Kazi Nazrul Islam', b_bn: 'কাজী নজরুল ইসলাম',
    c: 'Bankim Chandra Chattopadhyay', c_bn: 'বঙ্কিমচন্দ্র চট্টোপাধ্যায়',
    d: 'Michael Madhusudan Dutt', d_bn: 'মাইকেল মধুসূদন দত্ত',
    ans: 'A',
    exp: 'Rabindranath Tagore won the Nobel Prize in Literature in 1913 for "Gitanjali (Song Offerings)", becoming the first non-European and first Asian to win a Nobel Prize.',
    exp_bn: '১৯১৩ সালে গীতাঞ্জলি কাব্যগ্রন্থের ইংরেজি অনুবাদের জন্য রবীন্দ্রনাথ ঠাকুর সাহিত্যে এশিয়ার প্রথম নোবেল পুরস্কার অর্জন করেন।',
    fact: 'The English introduction to "Gitanjali" was written by famous Irish poet W. B. Yeats.',
    tip: 'Rabindranath Tagore is the composer of national anthems of two countries: India ("Jana Gana Mana") and Bangladesh ("Amar Shonar Bangla").'
  },
  {
    num: 10, subject_id: 'sub-geo-wb',
    text: 'Which is the highest mountain peak in South India (Peninsular India)?',
    text_bn: 'দক্ষিণ ভারত (উপদ্বীপীয় ভারত)-এর সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?',
    a: 'Anamudi (2,695 m, Annamalai Hills, Kerala)', a_bn: 'আনাইমুদি (২,৬৯৫ মি, আনাইমালাই পাহাড়, কেরালা)',
    b: 'Doddabetta (2,637 m, Nilgiri Hills, Tamil Nadu)', b_bn: 'দোদাবেত্তা (২,৬৩৭ মি, নীলগিরি পাহাড়, তামিলনাড়ু)',
    c: 'Kalsubai (1,646 m, Western Ghats)', c_bn: 'কালসুবাই (১,৬৪৬ মি)',
    d: 'Mahendragiri (1,501 m, Eastern Ghats)', d_bn: 'মহেন্দ্রগিরি (১,৫০১ মি)',
    ans: 'A',
    exp: 'Anamudi (elevation 2,695 meters / 8,842 ft) in the Annamalai Hills of the Western Ghats (Idukki district, Kerala) is the highest peak in South India and in India outside the Himalayas.',
    exp_bn: 'কেরালার ইদুক্কি জেলার আনাইমালাই পর্বতশ্রেণীর আনাইমুদি (২,৬৯৫ মিটার) দক্ষিণ ভারতের সর্বোচ্চ শৃঙ্গ।',
    fact: 'Doddabetta (2,637 m) is the highest peak of the Nilgiri Hills in Tamil Nadu.',
    tip: 'Rank 1 Peak in South India: Anamudi (2695m); Rank 2: Doddabetta (2637m).'
  },
  {
    num: 11, subject_id: 'sub-sci',
    text: 'Which vitamin is essential for blood clotting and synthesis of prothrombin?',
    text_bn: 'কোন ভিটামিন রক্ত জমাট বাঁধার জন্য এবং প্রথম্বিন সংশ্লেষের জন্য অপরিহার্য?',
    a: 'Vitamin K (Phylloquinone)', a_bn: 'ভিটামিন K (ফাইলোকুইনোন)',
    b: 'Vitamin A (Retinol)', b_bn: 'ভিটামিন A (রেটিনল)',
    c: 'Vitamin C (Ascorbic acid)', c_bn: 'ভিটামিন C (অ্যাসকরবিক অ্যাসিড)',
    d: 'Vitamin D (Calciferol)', d_bn: 'ভিটামিন D (ক্যালসিফেরল)',
    ans: 'A',
    exp: 'Vitamin K is required by the liver for synthesis of clotting factors II (prothrombin), VII, IX, and X. Deficiency leads to hemorrhage and prolonged bleeding.',
    exp_bn: 'ভিটামিন K যকৃতে প্রথম্বিন সংশ্লেষে সাহায্য করে এবং রক্ত জমাট বাঁধায় সহায়তা করে।',
    fact: 'Human intestinal bacteria (E. coli) synthesize Vitamin K2 (Menaquinone) naturally.',
    tip: 'Vitamins A, D, E, K = Fat-soluble.'
  },
  {
    num: 12, subject_id: 'sub-sci',
    text: 'A "Light Year" is a unit used to measure:',
    text_bn: '"আলোকবর্ষ" কী পরিমাপের একক?',
    a: 'Astronomical Distance', a_bn: 'জ্যোতির্বিজ্ঞান সংক্রান্ত দূরত্ব',
    b: 'Time duration', b_bn: 'সময়কাল',
    c: 'Intensity of light', c_bn: 'আলোর তীব্রতা',
    d: 'Solar mass', d_bn: 'সৌর ভর',
    ans: 'A',
    exp: 'A light-year is the distance light travels in one year in a vacuum (9.46 × 10^12 km).',
    exp_bn: 'শূন্য মাধ্যমে আলো এক বছরে যে দূরত্ব যায় তাকে আলোকবর্ষ বলে (৯.৪৬ × ১০^১২ কিমি)।',
    fact: '1 Parsec = 3.26 Light Years.',
    tip: 'Astronomical Units: AU < Light Year < Parsec.'
  },
  {
    num: 13, subject_id: 'sub-geo-wb',
    text: 'What is the highest mountain peak of West Bengal?',
    text_bn: 'পশ্চিমবঙ্গের সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?',
    a: 'Sandakphu (3,636 m)', a_bn: 'সান্দাকফু (৩,৬৩৬ মিটার)',
    b: 'Phalut (3,600 m)', b_bn: 'ফালুট (৩,৬০০ মিটার)',
    c: 'Tonglu (3,036 m)', c_bn: 'টংলু (৩,০৩৬ মিটার)',
    d: 'Sabargram (3,543 m)', d_bn: 'সবরগ্রাম (৩,৫৪৩ মিটার)',
    ans: 'A',
    exp: 'Sandakphu (3,636 m) on the Singalila Ridge in Darjeeling district is the highest point of West Bengal.',
    exp_bn: 'দার্জিলিং জেলার সিঙ্গালীলা শৈলশিরার সান্দাকফু (৩,৬৩৬ মিটার) পশ্চিমবঙ্গের সর্বোচ্চ শৃঙ্গ।',
    fact: 'Sandakphu is known as the "Trekkers\' Wonderland" on the Singalila National Park border.',
    tip: 'Sandakphu is higher than Phalut by 36 meters.'
  },
  {
    num: 14, subject_id: 'sub-hist',
    text: 'The historic Battle of Plassey took place on:',
    text_bn: 'ঐতিহাসিক পলাশীর যুদ্ধ সংঘটিত হয়েছিল:',
    a: '23rd June 1757', a_bn: '২৩শে জুন ১৭৫৭',
    b: '22nd October 1764', b_bn: '২২শে অক্টোবর ১৭৬৪',
    c: '14th January 1761', c_bn: '১৪ই জানুয়ারি ১৭৬১',
    d: '10th May 1857', d_bn: '১০ই মে ১৮৫৭',
    ans: 'A',
    exp: 'Battle of Plassey was fought on 23 June 1757 on the banks of Bhagirathi river in Nadia district between Robert Clive and Siraj-ud-Daulah.',
    exp_bn: '১৭৫৭ সালের ২৩শে জুন নদীয়া জেলার পলাশীর আমবাগানে সিরাজউদ্দৌলা ও ক্লাইভের বাহিনীর মধ্যে যুদ্ধ হয়।',
    fact: 'Mir Jafar became the Puppet Nawab of Bengal after the betrayal at Plassey.',
    tip: 'Plassey = 1757; Buxar = 1764; Diwani = 1765.'
  },
  {
    num: 15, subject_id: 'sub-ca',
    text: 'The Shanti Swarup Bhatnagar (SSB) Prize is given for outstanding contribution in:',
    text_bn: 'শান্তিস্বরূপ ভাটনগর পুরস্কার কোন ক্ষেত্রে অবদানের জন্য দেওয়া হয়?',
    a: 'Science and Technology', a_bn: 'বিজ্ঞান ও প্রযুক্তি',
    b: 'Literature', b_bn: 'সাহিত্য',
    c: 'Fine Arts & Music', c_bn: 'চারুকলা ও সঙ্গীত',
    d: 'Social Work', d_bn: 'সমাজসেবা',
    ans: 'A',
    exp: 'SSB Prize is given annually by CSIR for outstanding research in multidisciplinary Science & Technology.',
    exp_bn: 'CSIR প্রতি বছর বিজ্ঞান ও প্রযুক্তির গবেষণায় অবদানের জন্য শান্তিস্বরূপ ভাটনগর পুরস্কার প্রদান করে।',
    fact: 'Named after Dr. Shanti Swarup Bhatnagar, founder Director-General of CSIR.',
    tip: 'Age limit for SSB awardees is 45 years.'
  },
  {
    num: 16, subject_id: 'sub-geo-wb',
    text: 'Which is the largest river island in the world?',
    text_bn: 'বিশ্বের বৃহত্তম নদীদ্বীপ কোনটি?',
    a: 'Majuli (Assam, Brahmaputra River)', a_bn: 'মাজুলী (আসাম, ব্রহ্মপুত্র নদ)',
    b: 'Sagar Island (West Bengal)', b_bn: 'সাগর দ্বীপ (পশ্চিমবঙ্গ)',
    c: 'Marajo (Brazil)', c_bn: 'মারাজো (ব্রাজিল)',
    d: 'Umananda (Assam)', d_bn: 'উমানন্দ (আসাম)',
    ans: 'A',
    exp: 'Majuli on the Brahmaputra River in Assam is the largest inhabited river island in the world.',
    exp_bn: 'আসামের ব্রহ্মপুত্র নদের মাজুলী দ্বীপটি বিশ্বের বৃহত্তম নদীদ্বীপ।',
    fact: 'Majuli was declared a district of Assam in 2016, becoming India\'s first island district.',
    tip: 'Smallest river island = Umananda (Guwahati).'
  },
  {
    num: 17, subject_id: 'sub-polity',
    text: 'Who is the ex-officio Chairman of the Rajya Sabha?',
    text_bn: 'পদাধিকারবলে রাজ্যসভার চেয়ারম্যান কে হন?',
    a: 'Vice-President of India', a_bn: 'ভারতের উপরাষ্ট্রপতি',
    b: 'President of India', b_bn: 'ভারতের রাষ্ট্রপতি',
    c: 'Prime Minister of India', c_bn: 'ভারতের প্রধানমন্ত্রী',
    d: 'Speaker of Lok Sabha', d_bn: 'লোকসভার স্পিকার',
    ans: 'A',
    exp: 'Under Article 64 and Article 89(1), the Vice-President of India is the ex-officio Chairman of Rajya Sabha.',
    exp_bn: 'সংবিধানের ৬৪ অনুচ্ছেদ অনুযায়ী ভারতের উপরাষ্ট্রপতি রাজ্যসভার পদাধিকারবলে চেয়ারম্যান হন।',
    fact: 'The Vice-President presides over Rajya Sabha but is not a member of the House.',
    tip: 'Speaker leads Lok Sabha; Vice-President leads Rajya Sabha.'
  },
  {
    num: 18, subject_id: 'sub-ca',
    text: 'In which year did Prof. Amartya Sen receive the Nobel Prize in Economics?',
    text_bn: 'অধ্যাপক অমর্ত্য সেন কোন সালে অর্থনীতিতে নোবেল পুরস্কার লাভ করেন?',
    a: '1998', a_bn: '১৯৯৮',
    b: '1999', b_bn: '১৯৯৯',
    c: '1997', c_bn: '১৯৯৭',
    d: '2001', d_bn: '২০০১',
    ans: 'A',
    exp: 'Amartya Sen was awarded the 1998 Nobel Prize in Economics for his contributions to Welfare Economics.',
    exp_bn: 'কল্যাণ অর্থনীতিতে অবদানের জন্য অমর্ত্য সেন ১৯৯৮ সালে নোবেল পুরস্কার লাভ করেন।',
    fact: 'Sen was awarded the Bharat Ratna, India\'s highest civilian award, in 1999.',
    tip: 'Tagore (1913), Raman (1930), Mother Teresa (1979), Sen (1998), Banerjee (2019).'
  },
  {
    num: 19, subject_id: 'sub-ca',
    text: 'World Food Day is celebrated globally every year on:',
    text_bn: 'বিশ্ব খাদ্য দিবস প্রতি বছর কোন তারিখে পালিত হয়?',
    a: '16th October', a_bn: '১৬ই অক্টোবর',
    b: '5th June', b_bn: '৫ই জুন (পরিবেশ দিবস)',
    c: '22nd April', c_bn: '২২শে এপ্রিল (ধরিত্রী দিবস)',
    d: '1st December', d_bn: '১লা ডিসেম্বর (এইডস দিবস)',
    ans: 'A',
    exp: 'World Food Day is celebrated every year on 16 October to commemorate the founding date of the Food and Agriculture Organization (FAO) of the United Nations in 1945.',
    exp_bn: '১৯৪৫ সালের ১৬ই অক্টোবর জাতিসংঘের খাদ্য ও কৃষি সংস্থা (FAO) প্রতিষ্ঠার স্মরণে প্রতি বছর ১৬ই অক্টোবর বিশ্ব খাদ্য দিবস পালিত হয়।',
    fact: 'FAO headquarters is located in Rome, Italy.',
    tip: 'Important Days: 5 June = Environment Day; 16 Oct = World Food Day; 22 April = Earth Day.'
  },
  {
    num: 20, subject_id: 'sub-hist',
    text: 'In which country did the Industrial Revolution first begin in the 18th century?',
    text_bn: 'অষ্টাদশ শতকে শিল্পবিপ্লব প্রথম কোন দেশে শুরু হয়েছিল?',
    a: 'Great Britain (England)', a_bn: 'গ্রেট ব্রিটেন (ইংল্যান্ড)',
    b: 'France', b_bn: 'ফ্রান্স',
    c: 'Germany', c_bn: 'জার্মানি',
    d: 'United States of America', d_bn: 'মার্কিন যুক্তরাষ্ট্র',
    ans: 'A',
    exp: 'The Industrial Revolution began in Great Britain in the late 18th century (around 1760–1840), propelled by the steam engine, coal reserves, and mechanized textile manufacturing.',
    exp_bn: 'অষ্টাদশ শতাব্দীর মধ্যভাগে বাষ্পীয় ইঞ্জিন ও বস্ত্রশিল্পের যান্ত্রিকীকরণের মাধ্যমে ইংল্যান্ডে প্রথম শিল্পবিপ্লব শুরু হয়।',
    fact: 'James Watt patented the improved steam engine in 1769, powering the Industrial Revolution.',
    tip: 'First industry to be mechanized: Cotton Textile Industry in Lancashire and Manchester.'
  },
  {
    num: 21, subject_id: 'sub-inm',
    text: 'Who among the following was popularly known as "Frontier Gandhi" (Simanta Gandhi)?',
    text_bn: 'নিম্নলিখিতদের মধ্যে কে "সীমান্ত গান্ধী" নামে সমধিক পরিচিত ছিলেন?',
    a: 'Khan Abdul Ghaffar Khan (Badshah Khan)', a_bn: 'খান আব্দুল গফ্ফর খান (বাদশাহ খান)',
    b: 'Maulana Abul Kalam Azad', b_bn: 'মওলানা আবুল কালাম আজাদ',
    c: 'Mohammad Ali Jinnah', c_bn: 'মহম্মদ আলী জিন্নাহ',
    d: 'Shaukat Ali', d_bn: 'শওকত আলী',
    ans: 'A',
    exp: 'Khan Abdul Ghaffar Khan (also called Badshah Khan and Fakhr-e-Afghan) was a Pashtun independence activist who founded the non-violent Khudai Khidmatgar ("Red Shirts") movement and was known as Frontier Gandhi.',
    exp_bn: 'উত্তর-পশ্চিম সীমান্ত প্রদেশের অহিংস জাতীয়তাবাদী নেতা খান আব্দুল গফ্ফর খান "সীমান্ত গান্ধী" নামে পরিচিত ছিলেন। তিনি "খোদাই খিদমতগার" (লাল কুর্তা) দল গঠন করেন।',
    fact: 'In 1987, Khan Abdul Ghaffar Khan became the first non-Indian citizen to be awarded the Bharat Ratna.',
    tip: 'Two non-Indians with Bharat Ratna: Khan Abdul Ghaffar Khan (1987) and Nelson Mandela (1990).'
  },
  {
    num: 22, subject_id: 'sub-sci',
    text: 'Which gas is the major contributor to the Greenhouse Effect on Earth?',
    text_bn: 'পৃথিবীতে গ্রিনহাউস প্রভাবের (Greenhouse Effect) জন্য কোন গ্যাসটি প্রধানত দায়ী?',
    a: 'Carbon Dioxide (CO2)', a_bn: 'কার্বন ডাইঅক্সাইড (CO2)',
    b: 'Methane (CH4)', b_bn: 'মিথেন (CH4)',
    c: 'Nitrous Oxide (N2O)', c_bn: 'নাইট্রাস অক্সাইড (N2O)',
    d: 'Oxygen (O2)', d_bn: 'অক্সিজেন (O2)',
    ans: 'A',
    exp: 'Carbon Dioxide (CO2) is the primary greenhouse gas emitted through human activities (burning fossil fuels, deforestation) and is the main driver of global warming.',
    exp_bn: 'কার্বন ডাইঅক্সাইড (CO2) জীবাশ্ম জ্বালানি দহন ও শিল্পায়নের কারণে বায়ুমণ্ডলে সবচেয়ে বেশি পরিমাণে বৃদ্ধি পেয়ে গ্রিনহাউস প্রভাবের প্রধান কারণ হয়ে দাঁড়িয়েছে।',
    fact: 'Water vapor is the most abundant natural greenhouse gas, while CO2 is the primary anthropogenic driver.',
    tip: 'Oxygen and Nitrogen are NOT greenhouse gases because they are diatomic homonuclear molecules.'
  },
  {
    num: 23, subject_id: 'sub-sci',
    text: 'What is the chemical formula of Common Table Salt?',
    text_bn: 'সাধারণ খাবার লবণের রাসায়নিক সংকেত কোনটি?',
    a: 'NaCl (Sodium Chloride)', a_bn: 'NaCl (সোডিয়াম ক্লোরাইড)',
    b: 'NaHCO3 (Sodium Bicarbonate)', b_bn: 'NaHCO3 (সোডিয়াম বাইকার্বনেট)',
    c: 'Na2CO3 (Sodium Carbonate)', c_bn: 'Na2CO3 (সোডিয়াম কার্বনেট)',
    d: 'NaOH (Sodium Hydroxide)', d_bn: 'NaOH (সোডিয়াম হাইড্রোক্সাইড)',
    ans: 'A',
    exp: 'Common table salt is Sodium Chloride (NaCl), an ionic compound consisting of equal numbers of sodium and chlorine atoms.',
    exp_bn: 'খাবার লবণ হলো সোডিয়াম ক্লোরাইড (NaCl)।',
    fact: 'Baking Soda = NaHCO3; Washing Soda = Na2CO3·10H2O; Caustic Soda = NaOH.',
    tip: 'Common salt = NaCl; Rock salt is mineral Halite.'
  },
  {
    num: 24, subject_id: 'sub-polity',
    text: 'The concept of Fundamental Rights in the Indian Constitution was borrowed from the Constitution of:',
    text_bn: 'ভারতীয় সংবিধানে মৌলিক অধিকারের (Fundamental Rights) ধারণাটি কোন দেশের সংবিধান থেকে গৃহীত হয়েছে?',
    a: 'USA (Bill of Rights)', a_bn: 'মার্কিন যুক্তরাষ্ট্র (USA - Bill of Rights)',
    b: 'United Kingdom (UK)', b_bn: 'যুক্তরাজ্য (UK)',
    c: 'USSR (Soviet Union)', c_bn: 'সোভিয়েত ইউনিয়ন (USSR)',
    d: 'Ireland', d_bn: 'আয়ারল্যান্ড',
    ans: 'A',
    exp: 'Part III of the Indian Constitution (Articles 12 to 35) containing Fundamental Rights is inspired by the US Bill of Rights.',
    exp_bn: 'ভারতীয় সংবিধানের তৃতীয় অংশে (অনুচ্ছেদ ১২-৩৫) বর্ণিত মৌলিক অধিকারগুলি মার্কিন যুক্তরাষ্ট্রের সংবিধানের \'বিল অফ রাইটস\' থেকে গৃহীত।',
    fact: 'DPSP is borrowed from Ireland; Fundamental Duties from USSR; Parliamentary system from UK.',
    tip: 'USA = Fundamental Rights, Preamble, Judicial Review, Impeachment of President.'
  },
  {
    num: 25, subject_id: 'sub-geo-wb',
    text: 'The holy river Narmada originates from which mountain range / plateau?',
    text_bn: 'নর্মদা নদী কোন পর্বতশ্রেণী / মালভূমি থেকে উৎপত্তি লাভ করেছে?',
    a: 'Amarkantak Plateau (Maikal Range, MP)', a_bn: 'অমরকণ্টক মালভূমি (মাইকাল পর্বত, মধ্যপ্রদেশ)',
    b: 'Mahabaleshwar (Western Ghats)', b_bn: 'মহাবালেশ্বর (পশ্চিমঘাট পর্বত)',
    c: 'Nasik Trimbak Plateau', c_bn: 'ত্রয়ম্বকেশ্বর (নাসিক)',
    d: 'Betul Plateau (Satpura Range)', d_bn: 'মুলতাই (বেতুল মালভূমি)',
    ans: 'A',
    exp: 'The Narmada River originates from the Amarkantak Plateau in Anuppur district of Madhya Pradesh and flows westward through a rift valley between the Vindhya and Satpura ranges into the Arabian Sea.',
    exp_bn: 'নর্মদা নদী মধ্যপ্রদেশের অমরকণ্টক শৃঙ্গ থেকে উৎপন্ন হয়ে বিন্ধ্য ও সাতপুরা পর্বতের মধ্যবর্তী গ্রস্ত উপত্যকার মধ্য দিয়ে প্রবাহিত হয়ে খাম্বাত উপসাগরে পড়েছে।',
    fact: 'Dhuandhar Falls (Marble Rocks) near Jabalpur is formed on the Narmada River.',
    tip: 'West-flowing rivers into Arabian Sea: Narmada, Tapi, Mahi, Sabarmati.'
  },
  {
    num: 26, subject_id: 'sub-hist',
    text: 'Who constructed the Grand Trunk (GT) Road (Sadak-e-Azam) across Northern India?',
    text_bn: 'উত্তর ভারত জুড়ে বিখ্যাত গ্র্যান্ড ট্রাঙ্ক (GT) রোড (সড়ক-ই-আজম) কে নির্মাণ করেছিলেন?',
    a: 'Sher Shah Suri', a_bn: 'শেরশাহ সুরি',
    b: 'Akbar the Great', b_bn: 'সম্রাট আকবর',
    c: 'Ashoka the Great', c_bn: 'সম্রাট অশোক',
    d: 'Chandragupta Maurya', d_bn: 'চন্দ্রগুপ্ত মৌর্য',
    ans: 'A',
    exp: 'Sher Shah Suri (founder of the Sur Empire, 1540–1545) rebuilt the ancient royal highway connecting Sonargaon (Bengal) to Peshawar (now in Pakistan), known as Sadak-e-Azam (later renamed Grand Trunk Road by the British).',
    exp_bn: 'আফগান শাসক শেরশাহ সুরি সোনারগাঁও (বাংলা) থেকে পেশোয়ার পর্যন্ত সড়ক-ই-আজম (গ্র্যান্ড ট্রাঙ্ক রোড) নির্মাণ করেন।',
    fact: 'Sher Shah also introduced the silver coin called \'Rupiya\' (the precursor to modern Indian Rupee).',
    tip: 'Sher Shah\'s tomb is situated in Sasaram, Bihar in the middle of an artificial lake.'
  },
  {
    num: 27, subject_id: 'sub-sci',
    text: 'Which planet in our solar system is famously known as the "Red Planet"?',
    text_bn: 'সৌরজগতের কোন গ্রহটি "লাল গ্রহ" (Red Planet) নামে পরিচিত?',
    a: 'Mars', a_bn: 'মঙ্গল (Mars)',
    b: 'Venus', b_bn: 'শুক্র (Venus)',
    c: 'Jupiter', c_bn: 'বৃহস্পতি (Jupiter)',
    d: 'Saturn', d_bn: 'শনি (Saturn)',
    ans: 'A',
    exp: 'Mars appears reddish because of the widespread presence of Iron(III) Oxide (rust) on its surface and thin atmosphere.',
    exp_bn: 'মঙ্গল গ্রহের পৃষ্ঠতলে প্রচুর পরিমাণে আয়রন অক্সাইড (মরিচা) থাকায় এটি লালচে দেখায়, তাই একে লাল গ্রহ বলা হয়।',
    fact: 'Olympus Mons on Mars is the largest volcano and highest mountain in the Solar System (22 km high).',
    tip: 'Venus is the Morning/Evening Star; Mars is Red Planet; Jupiter is largest.'
  },
  {
    num: 28, subject_id: 'sub-geo-wb',
    text: 'In which year was the Sundarbans National Park declared a UNESCO World Heritage Site?',
    text_bn: 'সুন্দরবন জাতীয় উদ্যান কোন সালে ইউনেস্কো (UNESCO) ওয়ার্ল্ড হেরিটেজ সাইট হিসেবে স্বীকৃতি পায়?',
    a: '1987 (Natural World Heritage Site)', a_bn: '১৯৮৭ (প্রাকৃতিক বিশ্ব ঐতিহ্যবাহী স্থান)',
    b: '1989 (Biosphere Reserve)', b_bn: '১৯৮৯',
    c: '2001 (Ramsar Site)', c_bn: '২০০১',
    d: '1973 (Project Tiger)', d_bn: '১৯৭৩',
    ans: 'A',
    exp: 'Sundarbans National Park in West Bengal was inscribed as a UNESCO World Heritage Site in 1987 for its unique mangrove ecosystem and Royal Bengal Tiger habitat. It became a Ramsar Wetland of International Importance in 2019.',
    exp_bn: 'সুন্দরবন ১৯৮৭ সালে ইউনেস্কো কর্তৃক প্রাকৃতিক ওয়ার্ল্ড হেরিটেজ সাইটের মর্যাদা লাভ করে।',
    fact: 'The Sundarbans is the world\'s largest contiguous mangrove forest delta, formed by Ganga, Brahmaputra, and Meghna.',
    tip: 'UNESCO Site = 1987; Biosphere Reserve = 1989; Ramsar Wetland = 2019.'
  },
  {
    num: 29, subject_id: 'sub-inm',
    text: 'Who gave the famous slogan "Do or Die" (Karenge ya Marenge) during the Quit India Movement in 1942?',
    text_bn: '১৯৪২ সালের ভারত ছাড়ো আন্দোলনের সময় কে ঐতিহাসিক "করেঙ্গে ইয়া মরেঙ্গে" (Do or Die) স্লোগান দিয়েছিলেন?',
    a: 'Mahatma Gandhi', a_bn: 'মহাত্মা গান্ধী',
    b: 'Subhas Chandra Bose', b_bn: 'সুভাষচন্দ্র বসু',
    c: 'Jawaharlal Nehru', c_bn: 'জওহরলাল নেহরু',
    d: 'Bhagat Singh', d_bn: 'ভগত সিং',
    ans: 'A',
    exp: 'Mahatma Gandhi gave the call "Do or Die" in his speech at the Gowalia Tank Maidan in Bombay on 8 August 1942, launching the Quit India Movement.',
    exp_bn: '১৯৪২ সালের ৮ই আগস্ট বোম্বাইয়ের গোয়ালিয়া ট্যাঙ্ক ময়দানে ভারত ছাড়ো আন্দোলনের সূচনা করে গান্ধীজী এই ডাক দেন।',
    fact: 'Aruna Asaf Ali hoisted the Indian National Congress tricolour flag at Gowalia Tank during the Quit India movement.',
    tip: 'Gandhi = "Do or Die"; Subhas Bose = "Give me blood, I will give you freedom" / "Jai Hind"; Bhagat Singh = "Inquilab Zindabad".'
  },
  {
    num: 30, subject_id: 'sub-ca',
    text: 'What is the official currency of Japan?',
    text_bn: 'জাপানের সরকারি মুদ্রার নাম কী?',
    a: 'Japanese Yen (¥)', a_bn: 'ইয়েন (Yen - ¥)',
    b: 'Chinese Yuan (Renminbi)', b_bn: 'ইউয়ান (Yuan)',
    c: 'Korean Won (₩)', c_bn: 'ওয়ান (Won)',
    d: 'Thai Baht (฿)', d_bn: 'বাথ (Baht)',
    ans: 'A',
    exp: 'The official national currency of Japan is the Yen (¥, JPY).',
    exp_bn: 'জাপানের সরকারি মুদ্রার নাম হলো ইয়েন (Yen)।',
    fact: 'The Bank of Japan is the central bank of Japan, located in Tokyo.',
    tip: 'Currencies: Japan = Yen; China = Yuan (Renminbi); South Korea = Won; Russia = Ruble.'
  },
  {
    num: 31, subject_id: 'sub-sci',
    text: 'Which organ in the human body secretes the hormone Insulin?',
    text_bn: 'মানবদেহের কোন অঙ্গ ইনসুলিন হরমোন ক্ষরণ করে?',
    a: 'Pancreas (Beta cells of Islets of Langerhans)', a_bn: 'অগ্ন্যাশয় (আইলেটস অফ ল্যাঙ্গারহ্যান্সের বিটা কোষ)',
    b: 'Liver', b_bn: 'যকৃত',
    c: 'Thyroid Gland', c_bn: 'থাইরয়েড গ্রন্থি',
    d: 'Kidney', d_bn: 'বৃক্ক',
    ans: 'A',
    exp: 'Insulin is an endocrine peptide hormone produced by the Beta cells of the Islets of Langerhans in the pancreas, which regulates blood glucose levels by promoting absorption of glucose into liver, fat, and skeletal muscle cells.',
    exp_bn: 'অগ্ন্যাশয়ের আইলেটস অফ ল্যাঙ্গারহ্যান্সের বিটা কোষ থেকে ইনসুলিন ক্ষরিত হয়ে রক্তে শর্করার মাত্রা নিয়ন্ত্রণ করে।',
    fact: 'Insulin deficiency or resistance causes Diabetes Mellitus.',
    tip: 'Glucagon (raises blood sugar) is secreted by Alpha cells; Insulin (lowers blood sugar) by Beta cells.'
  },
  {
    num: 32, subject_id: 'sub-ca',
    text: 'What is the official capital city of Australia?',
    text_bn: 'অস্ট্রেলিয়ার সরকারি রাজধানী শহর কোনটি?',
    a: 'Canberra', a_bn: 'ক্যানবেরা (Canberra)',
    b: 'Sydney', b_bn: 'সিডনি (Sydney)',
    c: 'Melbourne', c_bn: 'মেলবোর্ন (Melbourne)',
    d: 'Brisbane', d_bn: 'ব্রিসবেন (Brisbane)',
    ans: 'A',
    exp: 'Canberra is the capital city of Australia, selected as a compromise between Sydney and Melbourne in 1908.',
    exp_bn: 'অস্ট্রেলিয়ার রাজধানী হলো ক্যানবেরা (সিডনি বা মেলবোর্ন নয়)।',
    fact: 'Canberra is an entirely planned city designed by American architect Walter Burley Griffin.',
    tip: 'Common confusion: Sydney and Melbourne are largest cities, but Canberra is the political capital.'
  },
  {
    num: 33, subject_id: 'sub-geo-wb',
    text: 'The Sundarbans National Park is internationally celebrated for preserving which endangered wildlife species?',
    text_bn: 'সুন্দরবন জাতীয় উদ্যান কোন বিপন্ন বন্যপ্রাণী সংরক্ষণের জন্য বিশ্বখ্যাত?',
    a: 'Royal Bengal Tiger (Panthera tigris tigris)', a_bn: 'রয়্যাল বেঙ্গল টাইগার (Royal Bengal Tiger)',
    b: 'One-horned Rhinoceros', b_bn: 'একশৃঙ্গ গণ্ডার',
    c: 'Snow Leopard', c_bn: 'তুষার চিতা',
    d: 'Asiatic Lion', d_bn: 'এশীয় সিংহ',
    ans: 'A',
    exp: 'The Sundarbans Mangrove delta is the largest natural reserve for the Royal Bengal Tiger, which is uniquely adapted to swimming in saline mangrove tidal channels.',
    exp_bn: 'সুন্দরবনের শ্বাসমূলীয় ম্যানগ্রোভ অরণ্য রয়্যাল বেঙ্গল টাইগারের বিশ্বের বৃহত্তম প্রাকৃতিক আবাসস্থল।',
    fact: 'Sundarbans is the only mangrove forest habitat in the world inhabited by tigers.',
    tip: 'Asiatic Lion = Gir (Gujarat); One-horned Rhino = Kaziranga (Assam); Royal Bengal Tiger = Sundarbans (WB).'
  },
  {
    num: 34, subject_id: 'sub-sci',
    text: 'What is the normal core body temperature of a healthy human being on the Fahrenheit and Celsius scales?',
    text_bn: 'একজন সুস্থ প্রাপ্তবয়স্ক মানুষের স্বাভাবিক শরীরের তাপমাত্রা ফারেনহাইট ও সেলসিয়াস স্কেলে কত?',
    a: '98.4°F to 98.6°F (37°C)', a_bn: '৯৮.৪°F - ৯৮.৬°F (৩৭°C)',
    b: '96.4°F (35°C)', b_bn: '৯৬.৪°F (৩৫°C)',
    c: '100.4°F (38°C)', c_bn: '১০০.৪°F (৩৮°C)',
    d: '94.2°F (34°C)', d_bn: '৯৪.২°F (৩৪°C)',
    ans: 'A',
    exp: 'The average normal body temperature is accepted as 98.6°F (37°C) or 98.4°F.',
    exp_bn: 'সুস্থ মানবদেহের স্বাভাবিক তাপমাত্রা প্রায় ৯৮.৪°F বা ৯৮.৬°F (৩৭°C)।',
    fact: 'Temperature conversion formula: C/5 = (F - 32)/9.',
    tip: 'At -40°, both Celsius and Fahrenheit scales indicate the exact same numerical reading (-40°C = -40°F).'
  },
  {
    num: 35, subject_id: 'sub-ca',
    text: 'Which country is internationally known as the "Land of White Elephants"?',
    text_bn: 'কোন দেশটিকে "শ্বেতহস্তীর দেশ" (Land of White Elephants) বলা হয়?',
    a: 'Thailand', a_bn: 'থাইল্যান্ড (Thailand)',
    b: 'Myanmar (Burma)', b_bn: 'মায়ানমার',
    c: 'Laos', c_bn: 'লাওস',
    d: 'Kenya', d_bn: 'কেনিয়া',
    ans: 'A',
    exp: 'Thailand is known as the Land of White Elephants, where white elephants (Chang Samkhan) are sacred symbols of royal power and prosperity.',
    exp_bn: 'থাইল্যান্ডকে শ্বেতহস্তীর দেশ বলা হয়, যেখানে সাদা হাতি রাজকীয় মর্যাদার প্রতীক।',
    fact: 'Laos is called the "Land of a Million Elephants" (Lan Xang).',
    tip: 'Land of Rising Sun = Japan; Land of Midnight Sun = Norway; Land of White Elephants = Thailand.'
  },
  {
    num: 36, subject_id: 'sub-polity',
    text: 'Under Article 75(3) of the Indian Constitution, the Union Council of Ministers is collectively responsible to:',
    text_bn: 'ভারতীয় সংবিধানের ৭৫(৩) অনুচ্ছেদ অনুযায়ী কেন্দ্রীয় মন্ত্রীপরিষদ যৌথভাবে কার কাছে দায়বদ্ধ থাকে?',
    a: 'The House of the People (Lok Sabha)', a_bn: 'লোকসভা (The House of the People)',
    b: 'The Council of States (Rajya Sabha)', b_bn: 'রাজ্যসভা',
    c: 'The President of India', c_bn: 'ভারতের রাষ্ট্রপতি',
    d: 'The Supreme Court of India', d_bn: 'ভারতের সুপ্রিম কোর্ট',
    ans: 'A',
    exp: 'Article 75(3) states that the Council of Ministers shall be collectively responsible to the House of the People (Lok Sabha).',
    exp_bn: 'সংবিধানের ৭৫(৩) ধারা অনুযায়ী কেন্দ্রীয় মন্ত্রীপরিষদ সমষ্টিগতভাবে লোকসভার কাছে দায়বদ্ধ থাকে।',
    fact: 'If a No-Confidence Motion is passed in the Lok Sabha, the entire Ministry must resign.',
    tip: 'Collective responsibility = Lok Sabha; Individual responsibility of a Minister = President (Art 75(2)).'
  },
  {
    num: 37, subject_id: 'sub-hist',
    text: 'Who founded the "Brahmo Samaj" in Calcutta in August 1828?',
    text_bn: '১৮২৮ সালের আগস্ট মাসে কলকাতায় "ব্রাহ্মসমাজ" কে প্রতিষ্ঠা করেন?',
    a: 'Raja Ram Mohan Roy', a_bn: 'রাজা রামমোহন রায়',
    b: 'Debendranath Tagore', b_bn: 'দেবেন্দ্রনাথ ঠাকুর',
    c: 'Keshab Chandra Sen', c_bn: 'কেশবচন্দ্র সেন',
    d: 'Swami Vivekananda', d_bn: 'স্বামী বিবেকানন্দ',
    ans: 'A',
    exp: 'Raja Ram Mohan Roy (the "Father of Indian Renaissance") founded the Brahmo Sabha in August 1828 (later renamed Brahmo Samaj) to propagate monotheism and fight social evils like Sati, idolatry, and casteism.',
    exp_bn: 'রাজা রামমোহন রায় ১৮২৮ সালের ২০শে আগস্ট কলকাতায় ব্রাহ্মসভা (পরবর্তীকালে ব্রাহ্মসমাজ) প্রতিষ্ঠা করেন।',
    fact: 'Mughal Emperor Akbar II conferred the title "Raja" upon Ram Mohan Roy in 1831.',
    tip: 'Ram Mohan Roy founded Atmiya Sabha in 1815 and Brahmo Samaj in 1828.'
  },
  {
    num: 38, subject_id: 'sub-geo-wb',
    text: 'Which state has the longest mainland coastline in India?',
    text_bn: 'ভারতের কোন রাজ্যের মূল ভূখণ্ডের উপকূলরেখার দৈর্ঘ্য দীর্ঘতম?',
    a: 'Gujarat (approx. 1,600 km)', a_bn: 'গুজরাট (প্রায় ১,৬০০ কিমি)',
    b: 'Andhra Pradesh (approx. 974 km)', b_bn: 'অন্ধ্রপ্রদেশ (প্রায় ৯৭৪ কিমি)',
    c: 'Tamil Nadu', c_bn: 'তামিলনাড়ু',
    d: 'Maharashtra', d_bn: 'মহারাষ্ট্র',
    ans: 'A',
    exp: 'Gujarat has the longest mainland coastline in India (~1,600 km), followed by Andhra Pradesh (second longest, ~974 km).',
    exp_bn: 'গুজরাটের উপকূলরেখা ভারতের সব রাজ্যের মধ্যে দীর্ঘতম (প্রায় ১,৬০০ কিমি)। অন্ধ্রপ্রদেশ দ্বিতীয় দীর্ঘতম।',
    fact: 'Total coastline of India (including islands) is 7,516.6 km across 9 coastal states.',
    tip: 'Longest coastline Rank 1: Gujarat; Rank 2: Andhra Pradesh; Rank 3: Tamil Nadu.'
  },
  {
    num: 39, subject_id: 'sub-sci',
    text: 'Which scientific instrument is used to measure Atmospheric Pressure?',
    text_bn: 'বায়ুমণ্ডলীয় চাপ পরিমাপ করার জন্য কোন বৈজ্ঞানিক যন্ত্র ব্যবহার করা হয়?',
    a: 'Barometer', a_bn: 'ব্যারোমিটার (Barometer)',
    b: 'Hygrometer (Measures Humidity)', b_bn: 'হাইগ্রোমিটার (আর্দ্রতা পরিমাপক)',
    c: 'Anemometer (Measures Wind Speed)', c_bn: 'অ্যানিমোমিটার (বায়ুর বেগ পরিমাপক)',
    d: 'Altimeter', d_bn: 'অল্টিমিটার',
    ans: 'A',
    exp: 'A Barometer, invented by Evangelista Torricelli in 1643, is an instrument used to measure atmospheric pressure.',
    exp_bn: 'বায়ুমণ্ডলের চাপ মাপার যন্ত্র হলো ব্যারোমিটার, যা ১৬৪৩ সালে টরিসেলি আবিষ্কার করেন।',
    fact: 'A sudden, sharp drop in barometer mercury reading indicates an impending storm/cyclone.',
    tip: 'Barometer = Pressure; Hygrometer = Humidity; Hydrometer = Liquid Density; Anemometer = Wind speed.'
  },
  {
    num: 40, subject_id: 'sub-sci',
    text: 'In which atmospheric layer is the protective Ozone Layer (O3) primarily concentrated?',
    text_bn: 'বায়ুমণ্ডলের কোন স্তরে সুরক্ষাকারী ওজোন স্তর (O3) প্রধানত কেন্দ্রীভূত থাকে?',
    a: 'Stratosphere (Ozonosphere, 15–35 km)', a_bn: 'স্ট্র্যাটোস্ফিয়ার (Stratosphere)',
    b: 'Troposphere (0–12 km)', b_bn: 'ট্রপোস্ফিয়ার',
    c: 'Mesosphere', c_bn: 'মেসোস্ফিয়ার',
    d: 'Thermosphere (Ionosphere)', d_bn: 'থার্মোস্ফিয়ার',
    ans: 'A',
    exp: 'About 90% of atmospheric ozone resides in the Stratosphere (15 to 35 km altitude), which absorbs harmful Solar Ultraviolet (UV-B) radiation.',
    exp_bn: 'বায়ুমণ্ডলের স্ট্র্যাটোস্ফিয়ারে ওজোন গ্যাসের প্রাচুর্য থাকে যা সূর্যের ক্ষতিকর অতিবেগুনি রশ্মি (UV rays) শোষণ করে পৃথিবীকে রক্ষা করে।',
    fact: 'Ozone thickness is measured in Dobson Units (DU). 16 September is celebrated as World Ozone Day.',
    tip: 'Atmospheric layers from ground up: Troposphere > Stratosphere > Mesosphere > Thermosphere > Exosphere.'
  },
  {
    num: 41, subject_id: 'sub-polity',
    text: 'Who was the Chairman of the Drafting Committee of the Constituent Assembly of India?',
    text_bn: 'ভারতের গণপরিষদের খসড়া কমিটির (Drafting Committee) চেয়ারম্যান কে ছিলেন?',
    a: 'Dr. B. R. Ambedkar (Father of Indian Constitution)', a_bn: 'ড. বি. আর. আম্বেদকর',
    b: 'Dr. Rajendra Prasad', b_bn: 'ড. রাজেন্দ্র প্রসাদ',
    c: 'Jawaharlal Nehru', c_bn: 'জওহরলাল নেহরু',
    d: 'B. N. Rau', d_bn: 'বি. এন. রাও',
    ans: 'A',
    exp: 'Dr. Bhimrao Ramji Ambedkar was appointed Chairman of the 7-member Drafting Committee on 29 August 1947.',
    exp_bn: '১৯৪৭ সালের ২৯শে আগস্ট গণপরিষদে গঠিত খসড়া কমিটির চেয়ারম্যান ছিলেন ড. বি. আর. আম্বেদকর।',
    fact: 'Sir B. N. Rau served as the Constitutional Advisor to the Constituent Assembly.',
    tip: 'President of Constituent Assembly = Dr. Rajendra Prasad; Drafting Committee Chairman = Dr. B. R. Ambedkar.'
  },
  {
    num: 42, subject_id: 'sub-polity',
    text: 'What is the constitutional minimum age requirement to contest election as a Member of Lok Sabha?',
    text_bn: 'লোকসভার সদস্য (MP) নির্বাচিত হওয়ার জন্য ন্যূনতম বয়স কত হওয়া প্রয়োজন?',
    a: '25 years', a_bn: '২৫ বছর',
    b: '30 years', b_bn: '৩০ বছর',
    c: '35 years', c_bn: '৩৫ বছর',
    d: '21 years', d_bn: '২১ বছর',
    ans: 'A',
    exp: 'Under Article 84(b) of the Constitution, a candidate must be not less than 25 years of age to be eligible for Lok Sabha, and not less than 30 years for Rajya Sabha.',
    exp_bn: 'সংবিধানের ৮৪(খ) অনুচ্ছেদ অনুযায়ী লোকসভার সদস্য হওয়ার ন্যূনতম বয়স ২৫ বছর এবং রাজ্যসভার জন্য ৩০ বছর।',
    fact: 'President and Governor require 35 years minimum age; Panchayat elections require 21 years.',
    tip: 'Age checklist: Panchayat/Municipality = 21y; Lok Sabha/Vidhan Sabha = 25y; Rajya Sabha/Vidhan Parishad = 30y; President/Governor = 35y.'
  },
  {
    num: 43, subject_id: 'sub-ben',
    text: 'The national song of India "Vande Mataram" was composed by Bankim Chandra Chattopadhyay in which famous novel?',
    text_bn: 'ভারতের জাতীয় স্তোত্র "বন্দে মাতরম্" বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের কোন বিখ্যাত উপন্যাসের অন্তর্ভুক্ত?',
    a: 'Anandamath (Published 1882)', a_bn: 'আনন্দমঠ (১৮৮২)',
    b: 'Durgeshnandini (1865)', b_bn: 'দুর্গেশনন্দিনী',
    c: 'Kapalkundala (1866)', c_bn: 'কপালকুণ্ডলা',
    d: 'Devi Chaudhurani (1884)', d_bn: 'দেবী চৌধুরাণী',
    ans: 'A',
    exp: '"Vande Mataram" was composed in Sanskrit-Bengali by Bankim Chandra Chattopadhyay in his 1882 novel "Anandamath", set against the backdrop of the Sannyasi Rebellion in Bengal.',
    exp_bn: '১৮৮২ সালে প্রকাশিত বঙ্কিমচন্দ্রের "আনন্দমঠ" উপন্যাসে সন্ন্যাসী বিদ্রোহের পটভূমিতে "বন্দে মাতরম্" গানটি রচিত হয়।',
    fact: 'First sung politically by Rabindranath Tagore at the 1896 Calcutta Session of INC.',
    tip: 'National Anthem ("Jana Gana Mana") = Rabindranath Tagore; National Song ("Vande Mataram") = Bankim Chandra Chattopadhyay.'
  },
  {
    num: 44, subject_id: 'sub-geo-wb',
    text: 'Which state in India possesses the largest forest cover by area according to the India State of Forest Report (ISFR)?',
    text_bn: 'ফরেস্ট রিপোর্ট অনুযায়ী ভারতের কোন রাজ্যে আয়তনের নিরিখে সর্বাধিক অরণ্যাবৃত অঞ্চল রয়েছে?',
    a: 'Madhya Pradesh (MP)', a_bn: 'মধ্যপ্রদেশ (Madhya Pradesh)',
    b: 'Arunachal Pradesh', b_bn: 'অরুণাচল প্রদেশ',
    c: 'Chhattisgarh', c_bn: 'ছত্তিশগড়',
    d: 'Odisha', d_bn: 'ওড়িশা',
    ans: 'A',
    exp: 'Madhya Pradesh has the largest forest cover in the country by area, followed by Arunachal Pradesh and Chhattisgarh.',
    exp_bn: 'আয়তনের দিক থেকে ভারতের মধ্যপ্রদেশে সর্বাধিক বনাঞ্চল রয়েছে, তারপরেই রয়েছে অরুণাচল প্রদেশ।',
    fact: 'By percentage of total geographical area, Mizoram has the highest forest cover (approx. 84.5%).',
    tip: 'Largest Forest by Area = Madhya Pradesh; Highest Forest by Percentage = Mizoram.'
  },
  {
    num: 45, subject_id: 'sub-polity',
    text: 'Who was the first Chief Justice of the Supreme Court of independent India?',
    text_bn: 'স্বাধীন ভারতের সুপ্রিম কোর্টের প্রথম প্রধান বিচারপতি কে ছিলেন?',
    a: 'Justice H. J. Kania (Hiralal Jekisundas Kania)', a_bn: 'বিচারপতি এইচ. জে. কানিয়া (হীরালাল জে. কানিয়া)',
    b: 'Justice M. Patanjali Sastri', b_bn: 'বিচারপতি এম. পতঞ্জলি শাস্ত্রী',
    c: 'Justice Mehr Chand Mahajan', c_bn: 'বিচারপতি মেহের চাঁদ মহাজন',
    d: 'Justice Sudhi Ranjan Das', d_bn: 'বিচারপতি সুধীরঞ্জন দাশ',
    ans: 'A',
    exp: 'Justice H. J. Kania served as the First Chief Justice of India from 26 January 1950 until his death in office in November 1951.',
    exp_bn: '১৯৫০ সালের ২৬শে জানুয়ারি সুপ্রিম কোর্ট প্রতিষ্ঠার পর বিচারপতি হীরালাল জেকিসুনদাস কানিয়া ভারতের প্রথম প্রধান বিচারপতি নিযুক্ত হন।',
    fact: 'First female judge of the Supreme Court was Justice M. Fathima Beevi (1989).',
    tip: 'Supreme Court was inaugurated on 28 January 1950 under Article 124.'
  },
  {
    num: 46, subject_id: 'sub-sci',
    text: 'Which metal is the best conductor of electricity among all elements?',
    text_bn: 'সকল মৌলিক পদার্থের মধ্যে কোন ধাতুর বিদ্যুৎ পরিবাহিতা (Electrical Conductivity) সর্বোচ্চ?',
    a: 'Silver (Argentum - Ag)', a_bn: 'রূপা (Silver - Ag)',
    b: 'Copper (Cu)', b_bn: 'তামা (Copper - Cu)',
    c: 'Gold (Au)', c_bn: 'স্বর্ণ (Gold - Au)',
    d: 'Aluminium (Al)', d_bn: 'অ্যালুমিনিয়াম (Al)',
    ans: 'A',
    exp: 'Silver (Ag) has the highest electrical conductivity of any known element, followed by Copper (Cu) and Gold (Au).',
    exp_bn: 'রূপা (Silver) হলো বিদ্যুতের সর্বোত্তম পরিবাহী ধাতু, যার পরেই রয়েছে তামা।',
    fact: 'Copper and Aluminium are used in electrical cables due to affordability, even though silver is a superior conductor.',
    tip: 'Conductivity order: Silver (Ag) > Copper (Cu) > Gold (Au) > Aluminium (Al).'
  },
  {
    num: 47, subject_id: 'sub-geo-wb',
    text: 'Kaziranga National Park in Assam is world-famous for the conservation of:',
    text_bn: 'আসামের কাজিরাঙ্গা জাতীয় উদ্যান কোন প্রাণীর সংরক্ষণের জন্য বিশ্বখ্যাত?',
    a: 'Great One-horned Rhinoceros (Rhinoceros unicornis)', a_bn: 'ভারতীয় একশৃঙ্গ গণ্ডার (One-horned Rhinoceros)',
    b: 'Royal Bengal Tiger', b_bn: 'রয়্যাল বেঙ্গল টাইগার',
    c: 'Asiatic Elephant', b_bn: 'এশীয় হাতি',
    d: 'Snow Leopard', d_bn: 'তুষার চিতা',
    ans: 'A',
    exp: 'Kaziranga National Park in Golaghat and Nagaon districts of Assam hosts two-thirds of the world\'s great one-horned rhinoceroses and is a UNESCO World Heritage Site.',
    exp_bn: 'আসামের কাজিরাঙ্গা জাতীয় উদ্যান বিশ্বের দুই-তৃতীয়াংশ একশৃঙ্গ গণ্ডারের আবাসস্থল হিসেবে ইউনেস্কো ওয়ার্ল্ড হেরিটেজ সাইট।',
    fact: 'Kaziranga is also a Tiger Reserve with one of the highest densities of tigers in the world.',
    tip: 'Kaziranga = One-horned Rhino (Assam); Gir = Asiatic Lion (Gujarat); Manas = Golden Langur (Assam).'
  },
  {
    num: 48, subject_id: 'sub-polity',
    text: 'The Planning Commission of India was dissolved and replaced by which think-tank on 1st January 2015?',
    text_bn: '২০১৫ সালের ১লা জানুয়ারি যোজনা কমিশনের (Planning Commission) পরিবর্তে কোন প্রতিষ্ঠানটি গঠিত হয়?',
    a: 'NITI Aayog (National Institution for Transforming India)', a_bn: 'নীতি আয়োগ (NITI Aayog)',
    b: 'National Development Council (NDC)', b_bn: 'জাতীয় উন্নয়ন পরিষদ',
    c: 'Finance Commission of India', c_bn: 'অর্থ কমিশন',
    d: 'Inter-State Council', d_bn: 'আন্তঃরাজ্য পরিষদ',
    ans: 'A',
    exp: 'NITI Aayog (National Institution for Transforming India) replaced the 65-year-old Planning Commission on 1 January 2015 as the premier policy think-tank of the Government of India.',
    exp_bn: '২০১৫ সালের ১লা জানুয়ারি কেন্দ্রীয় সরকার যোজনা কমিশনের অবলুপ্তি ঘটিয়ে "নীতি আয়োগ" (NITI Aayog) গঠন করে।',
    fact: 'The Prime Minister of India serves as the ex-officio Chairperson of NITI Aayog.',
    tip: 'NITI stands for "National Institution for Transforming India".'
  },
  {
    num: 49, subject_id: 'sub-sci',
    text: 'Sound waves cannot travel through which of the following media?',
    text_bn: 'শব্দ তরঙ্গ নিম্নলিখিত কোন মাধ্যমের মধ্য দিয়ে চলাচল করতে পারে না?',
    a: 'Vacuum (Empty space)', a_bn: 'শূন্যস্থান (Vacuum)',
    b: 'Solid steel', b_bn: 'কঠিন ইস্পাত',
    c: 'Liquid water', c_bn: 'তরল জল',
    d: 'Gaseous air', d_bn: 'বায়ু মাধ্যম',
    ans: 'A',
    exp: 'Sound is a mechanical longitudinal wave that requires a material medium (solid, liquid, or gas) to propagate. It cannot travel through a vacuum.',
    exp_bn: 'শব্দ একটি স্থিতিস্থাপক অনুদৈর্ঘ্য তরঙ্গ, যা চলাচলের জন্য জড় মাধ্যমের প্রয়োজন হয়। শূন্যস্থানে কোনো অণু না থাকায় শব্দ চলাচল করতে পারে না।',
    fact: 'Speed of sound is fastest in solids (~5960 m/s in steel), slower in liquids (~1480 m/s in water), and slowest in gases (~343 m/s in air).',
    tip: 'Light can travel through a vacuum; Sound CANNOT.'
  },
  {
    num: 50, subject_id: 'sub-geo-wb',
    text: 'Which is the longest river in Peninsular India, often called the "Dakshin Ganga"?',
    text_bn: 'উপদ্বীপীয় ভারতের দীর্ঘতম নদী কোনটি, যাকে "দক্ষিণ গঙ্গা" (Dakshin Ganga) বলা হয়?',
    a: 'Godavari (Length approx. 1,465 km)', a_bn: 'গোদাবরী (দৈর্ঘ্য প্রায় ১,৪৬৫ কিমি)',
    b: 'Krishna (approx. 1,400 km)', b_bn: 'কৃষ্ণা',
    c: 'Mahanadi (approx. 858 km)', c_bn: 'মহানদী',
    d: 'Cauvery (Kaveri, 800 km)', d_bn: 'কাবেরী',
    ans: 'A',
    exp: 'The Godavari (1,465 km), originating from Trimbakeshwar in Maharashtra, is the longest river in Peninsular India and second longest in India after Ganga. It is called "Dakshin Ganga" or "Vriddha Ganga".',
    exp_bn: 'মহারাষ্ট্রের ত্রয়ম্বকেশ্বর থেকে উৎপন্ন গোদাবরী (১,৪৬৫ কিমি) উপদ্বীপীয় ভারতের দীর্ঘতম নদী এবং একে "দক্ষিণ গঙ্গা" বা "বৃদ্ধ গঙ্গা" বলা হয়।',
    fact: 'Kaveri is known as "Ganga of the South" for its perennial sacred status.',
    tip: 'Longest river in India = Ganga (2525 km); Longest peninsular river = Godavari (1465 km).'
  },

  // --- ARITHMETIC & NUMERICAL ABILITY (Q51 to Q100) ---
  {
    num: 51, subject_id: 'sub-arith',
    text: 'A sum of money doubles itself in 10 years at simple interest. What is the rate of interest per annum?',
    text_bn: 'কোনো আসল সরল সুদে ১০ বছরে দ্বিগুণ হয়। বার্ষিক সুদের হার কত?',
    a: '10% per annum', a_bn: '১০% বার্ষিক',
    b: '8% per annum', b_bn: '৮% বার্ষিক',
    c: '12% per annum', c_bn: '১২% বার্ষিক',
    d: '15% per annum', d_bn: '১৫% বার্ষিক',
    ans: 'A',
    exp: 'Let Principal = P. Amount = 2P, so SI = P.\nSI = (P × R × T)/100 => P = (P × R × 10)/100 => R = 10% per annum.',
    exp_bn: 'SI = P. সূত্রানুযায়ী R = (১০০ × SI)/(P × T) = (১০০ × P)/(P × ১০) = ১০%।',
    fact: 'Formula: R = 100(N - 1) / T.',
    tip: 'R × T = 100 for doubling.'
  },
  {
    num: 52, subject_id: 'sub-arith',
    text: 'The present ages of A and B are in the ratio 3:4. Four years ago, the ratio of their ages was 2:3. What is the present age of B?',
    text_bn: 'A এবং B-এর বর্তমান বয়সের অনুপাত ৩:৪। চার বছর পূর্বে তাদের বয়সের অনুপাত ছিল ২:৩। B-এর বর্তমান বয়স কত?',
    a: '16 years', a_bn: '১৬ বছর',
    b: '12 years', b_bn: '১২ বছর',
    c: '20 years', c_bn: '২০ বছর',
    d: '24 years', d_bn: '২৪ বছর',
    ans: 'A',
    exp: 'Let current ages be 3x and 4x.\n(3x - 4)/(4x - 4) = 2/3 => 9x - 12 = 8x - 8 => x = 4.\nPresent age of B = 4 × 4 = 16 years.',
    exp_bn: '(৩x - ৪)/(৪x - ৪) = ২/৩ => ৯x - ১২ = ৮x - ৮ => x = ৪। অতএব B-এর বয়স = ৪ × ৪ = ১৬ বছর।',
    fact: 'Difference in ratio units is 1 unit = 4 years.',
    tip: 'B\'s age = 4 units × 4 = 16.'
  },
  {
    num: 53, subject_id: 'sub-arith',
    text: 'A train 150 meters long crosses a telegraph post in 15 seconds. What is the speed of the train in km/h?',
    text_bn: '১৫০ মিটার দীর্ঘ একটি ট্রেন ১৫ সেকেন্ডে একটি টেলিগ্রাফ পোস্ট অতিক্রম করে। ট্রেনটির গতিবেগ ঘণ্টায় কত কিমি?',
    a: '36 km/h', a_bn: '৩৬ কিমি/ঘণ্টা',
    b: '45 km/h', b_bn: '৪৫ কিমি/ঘণ্টা',
    c: '54 km/h', c_bn: '৫৪ কিমি/ঘণ্টা',
    d: '30 km/h', d_bn: '৩০ কিমি/ঘণ্টা',
    ans: 'A',
    exp: 'Speed in m/s = Distance / Time = 150 m / 15 s = 10 m/s.\nSpeed in km/h = 10 × (18 / 5) = 36 km/h.',
    exp_bn: 'গতিবেগ = ১৫০/১৫ = ১০ মিটার/সেকেন্ড। কিমি/ঘণ্টায় রূপান্তর = ১০ × ১৮/৫ = ৩৬ কিমি/ঘণ্টা।',
    fact: 'To convert m/s to km/h, multiply by 18/5.',
    tip: '10 m/s = 36 km/h; 15 m/s = 54 km/h; 20 m/s = 72 km/h.'
  },
  {
    num: 54, subject_id: 'sub-arith',
    text: 'If 12 men can complete a piece of work in 20 days, how many days will 15 men take to complete the same work?',
    text_bn: '১২ জন লোক একটি কাজ ২০ দিনে শেষ করতে পারে। ওই কাজটি ১৫ জন লোক কত দিনে শেষ করতে পারবে?',
    a: '16 days', a_bn: '১৬ দিন',
    b: '18 days', b_bn: '১৮ দিন',
    c: '15 days', c_bn: '১৫ দিন',
    d: '25 days', d_bn: '২৫ দিন',
    ans: 'A',
    exp: 'M1 × D1 = M2 × D2\n12 × 20 = 15 × D2 => 240 = 15 × D2 => D2 = 240 / 15 = 16 days.',
    exp_bn: 'M1 × D1 = M2 × D2 => ১২ × ২০ = ১৫ × D2 => D2 = ২৪০ / ১৫ = ১৬ দিন।',
    fact: 'Work is inversely proportional to number of men.',
    tip: '12 × 20 / 15 = 4 × 4 = 16 days.'
  },
  {
    num: 55, subject_id: 'sub-arith',
    text: 'A shopkeeper sells an article for Rs. 450 incurring a loss of 10%. At what selling price should he sell it to gain 20%?',
    text_bn: 'একজন দোকানদার ৪৫০ টাকায় একটি জিনিস বিক্রি করে ১০% ক্ষতির সম্মুখীন হন। ২০% লাভ করতে হলে জিনিসটি কত টাকায় বিক্রি করতে হবে?',
    a: 'Rs. 600', a_bn: '৬০০ টাকা',
    b: 'Rs. 540', b_bn: '৫৪০ টাকা',
    c: 'Rs. 580', c_bn: '৫৮০ টাকা',
    d: 'Rs. 650', d_bn: '৬৫০ টাকা',
    ans: 'A',
    exp: 'Cost Price (CP) = SP / (1 - Loss%) = 450 / 0.9 = Rs. 500.\nTarget SP for 20% gain = CP × 1.20 = 500 × 1.20 = Rs. 600.',
    exp_bn: 'ক্রয়মূল্য = ৪৫০ / ০.৯ = ৫০০ টাকা। ২০% লাভে বিক্রয়মূল্য = ৫০০ × ১.২ = ৬০০ টাকা।',
    fact: 'Direct formula: Target SP = 450 × (120 / 90) = 450 × (4/3) = Rs. 600.',
    tip: 'Direct shortcut: 450 × 120 / 90 = 600.'
  },
  {
    num: 56, subject_id: 'sub-arith',
    text: 'The average of 5 consecutive odd numbers is 27. What is the largest of these numbers?',
    text_bn: '৫টি পরপর বিজোড় সংখ্যার গড় ২৭। এদের মধ্যে বৃহত্তম সংখ্যাটি কত?',
    a: '31', a_bn: '৩১',
    b: '29', b_bn: '২৯',
    c: '33', c_bn: '৩৩',
    d: '35', d_bn: '৩৫',
    ans: 'A',
    exp: 'The average of consecutive odd numbers is the exact middle number. Here Middle number (3rd) = 27.\nThe 5 numbers are: 23, 25, 27, 29, 31. Largest number = 31.',
    exp_bn: 'পরপর বিজোড় সংখ্যার গড় হলো মধ্যবর্তী সংখ্যা। এখানে মধ্য সংখ্যা = ২৭। সংখ্যা ৫টি হলো: ২৩, ২৫, ২৭, ২৯, ৩১। বৃহত্তম সংখ্যা = ৩১।',
    fact: 'Largest = Average + (n - 1) = 27 + 4 = 31.',
    tip: 'Smallest = 27 - 4 = 23; Largest = 27 + 4 = 31.'
  },
  {
    num: 57, subject_id: 'sub-arith',
    text: 'What is the Highest Common Factor (HCF / গ.সা.গু.) of 36, 54, and 90?',
    text_bn: '৩৬, ৫৪ এবং ৯০-এর গরিষ্ঠ সাধারণ গুণনীয়ক (গ.সা.গু. / HCF) কত?',
    a: '18', a_bn: '১৮',
    b: '9', b_bn: '৯',
    c: '12', c_bn: '১২',
    d: '6', d_bn: '৬',
    ans: 'A',
    exp: '36 = 18 × 2\n54 = 18 × 3\n90 = 18 × 5\nGreatest common divisor is 18.',
    exp_bn: '৩৬ = ১৮ × ২, ৫৪ = ১৮ × ৩, ৯০ = ১৮ × ৫। সাধারণ সর্বোচ্চ গুণনীয়ক হলো ১৮।',
    fact: 'Difference method: 54 - 36 = 18; 90 - 54 = 36. HCF of (18, 36) = 18.',
    tip: 'HCF divides all differences between numbers.'
  },
  {
    num: 58, subject_id: 'sub-arith',
    text: 'Two pipes A and B can fill a cistern in 12 hours and 18 hours respectively. If both pipes are opened simultaneously, how long will they take to fill the cistern?',
    text_bn: 'দুটি নল A ও B একটি জলাধার যথাক্রমে ১২ ঘণ্টা ও ১৮ ঘণ্টায় পূর্ণ করতে পারে। দুটি নল একসাথে খুলে দিলে জলাধারটি কত সময়ে পূর্ণ হবে?',
    a: '7.2 hours (7 hours 12 minutes)', a_bn: '৭.২ ঘণ্টা (৭ ঘণ্টা ১২ মিনিট)',
    b: '8 hours', b_bn: '৮ ঘণ্টা',
    c: '6.5 hours', c_bn: '৬.৫ ঘণ্টা',
    d: '7.5 hours', d_bn: '৭.৫ ঘণ্টা',
    ans: 'A',
    exp: 'Combined rate = 1/12 + 1/18 = (3 + 2)/36 = 5/36 per hour.\nTime to fill = 36/5 = 7.2 hours = 7 hours and (0.2 × 60) = 7 hours 12 minutes.',
    exp_bn: 'একত্রে ১ ঘণ্টায় পূর্ণ করে = ১/১২ + ১/১৮ = ৫/৩৬ অংশ। পুরো জলাধার পূর্ণ হতে সময় লাগবে = ৩৬/৫ = ৭.২ ঘণ্টা = ৭ ঘণ্টা ১২ মিনিট।',
    fact: 'Product / Sum formula: (12 × 18) / (12 + 18) = 216 / 30 = 7.2 hours.',
    tip: '0.2 hours = 0.2 × 60 = 12 minutes.'
  },
  {
    num: 59, subject_id: 'sub-arith',
    text: 'If 25% of a certain number is 75, what is 40% of that number?',
    text_bn: 'যদি কোনো সংখ্যার ২৫% সমান ৭৫ হয়, তবে ওই সংখ্যাটির ৪০% কত হবে?',
    a: '120', a_bn: '১২০',
    b: '100', b_bn: '১০০',
    c: '150', c_bn: '১৫০',
    d: '180', d_bn: '১৮০',
    ans: 'A',
    exp: '25% of X = 75 => X = 75 / 0.25 = 300.\n40% of 300 = 300 × 0.40 = 120.',
    exp_bn: '২৫% = ৭৫ => ১০০% = ৩০০। অতএব ৪০% = ৩০০ × ৪০/১০০ = ১২০।',
    fact: 'Direct ratio: 75 × (40 / 25) = 75 × 1.6 = 120.',
    tip: '40/25 = 8/5; 75 × 8/5 = 120.'
  },
  {
    num: 60, subject_id: 'sub-arith',
    text: 'A merchant purchases a wristwatch for Rs. 800 and sells it for Rs. 1000. What is his percentage profit?',
    text_bn: 'একজন ব্যবসায়ী ৮০০ টাকায় একটি হাতঘড়ি কিনে ১০০০ টাকায় বিক্রি করেন। তার শতকরা লাভের হার কত?',
    a: '25%', a_bn: '২৫%',
    b: '20%', b_bn: '২০%',
    c: '15%', c_bn: '১৫%',
    d: '30%', d_bn: '৩০%',
    ans: 'A',
    exp: 'Profit = SP - CP = 1000 - 800 = Rs. 200.\nProfit % = (Profit / CP) × 100 = (200 / 800) × 100 = 25%.',
    exp_bn: 'লাভ = ১০০০ - ৮০০ = ২০০ টাকা। শতকরা লাভ = (২০০ / ৮০০) × ১০০ = ২৫%।',
    fact: 'Profit percentage is always computed on Cost Price unless specified otherwise.',
    tip: '200/800 = 1/4 = 25%.'
  },
  {
    num: 61, subject_id: 'sub-arith',
    text: 'What is the compound interest on Rs. 10,000 for 2 years at 10% per annum compounded annually?',
    text_bn: 'বার্ষিক ১০% চক্রবৃদ্ধি সুদে ১০,০০০ টাকার ২ বছরের চক্রবৃদ্ধি সুদ কত?',
    a: 'Rs. 2,100', a_bn: '২,১০০ টাকা',
    b: 'Rs. 2,000', b_bn: '২,০০০ টাকা',
    c: 'Rs. 2,200', c_bn: '২,২০০ টাকা',
    d: 'Rs. 1,900', d_bn: '১,৯০০ টাকা',
    ans: 'A',
    exp: 'Amount A = P(1 + R/100)^T = 10000 × (1.10)^2 = 10000 × 1.21 = Rs. 12,100.\nCompound Interest = Amount - Principal = 12100 - 10000 = Rs. 2,100.',
    exp_bn: 'সুদ-আসল = ১০,০০০ × (১.১)^২ = ১২,১০০ টাকা। চক্রবৃদ্ধি সুদ = ১২,১০০ - ১০,০০০ = ২,১০০ টাকা।',
    fact: 'Effective CI rate for 2 years at 10% = 10 + 10 + (10×10)/100 = 21%. 21% of 10000 = Rs. 2100.',
    tip: 'Use effective rate: 21% of 10000 = 2100.'
  },
  {
    num: 62, subject_id: 'sub-arith',
    text: 'The perimeter of a rectangle is 48 cm and its length is 14 cm. What is the area of the rectangle?',
    text_bn: 'একটি আয়তক্ষেত্রের পরিসীমা ৪৮ সেমি এবং দৈর্ঘ্য ১৪ সেমি। আয়তক্ষেত্রটির ক্ষেত্রফল কত?',
    a: '140 sq cm', a_bn: '১৪০ বর্গ সেমি',
    b: '120 sq cm', b_bn: '১২০ বর্গ সেমি',
    c: '150 sq cm', c_bn: '১৫০ বর্গ সেমি',
    d: '160 sq cm', d_bn: '১৬০ বর্গ সেমি',
    ans: 'A',
    exp: 'Perimeter = 2(L + B) = 48 => L + B = 24.\nBreadth B = 24 - 14 = 10 cm.\nArea = Length × Breadth = 14 × 10 = 140 sq cm.',
    exp_bn: '২(দৈর্ঘ্য + প্রস্থ) = ৪৮ => দৈর্ঘ্য + প্রস্থ = ২৪। প্রস্থ = ২৪ - ১৪ = ১০ সেমি। ক্ষেত্রফল = ১৪ × ১০ = ১৪০ বর্গ সেমি।',
    fact: 'Area of rectangle = L × B; Perimeter = 2(L + B).',
    tip: 'L + B is always half of perimeter.'
  },
  {
    num: 63, subject_id: 'sub-arith',
    text: 'If A : B = 2 : 3 and B : C = 4 : 5, find the compound ratio A : B : C.',
    text_bn: 'যদি A : B = ২ : ৩ এবং B : C = ৪ : ৫ হয়, তবে A : B : C নির্ণয় করুন।',
    a: '8 : 12 : 15', a_bn: '৮ : ১২ : ১৫',
    b: '6 : 9 : 15', b_bn: '৬ : ৯ : ১৫',
    c: '8 : 10 : 15', c_bn: '৮ : ১০ : ১৫',
    d: '2 : 4 : 5', d_bn: '২ : ৪ : ৫',
    ans: 'A',
    exp: 'Multiply first ratio by 4 and second ratio by 3 to equalize B:\nA : B = 8 : 12\nB : C = 12 : 15\nCombined ratio A : B : C = 8 : 12 : 15.',
    exp_bn: 'B কে সমান করলে: A:B = ৮:১২ এবং B:C = ১২:১৫। অতএব A:B:C = ৮:১২:১৫।',
    fact: 'A:B:C = (2×4) : (3×4) : (3×5) = 8 : 12 : 15.',
    tip: 'Multiply vertically: A = 2×4 = 8; B = 3×4 = 12; C = 3×5 = 15.'
  },
  {
    num: 64, subject_id: 'sub-arith',
    text: 'By selling 33 meters of cloth, a merchant gains the cost price of 11 meters. What is his percentage profit?',
    text_bn: '৩৩ মিটার কাপড় বিক্রি করে একজন ব্যবসায়ী ১১ মিটার কাপড়ের ক্রয়মূল্যের সমান লাভ করেন। তার শতকরা লাভের হার কত?',
    a: '33 1/3% (33.33%)', a_bn: '৩৩ ১/৩% (৩৩.৩৩%)',
    b: '25%', b_bn: '২৫%',
    c: '20%', c_bn: '২০%',
    d: '50%', d_bn: '৫০%',
    ans: 'A',
    exp: 'Let CP of 1 meter cloth = Rs. 1. CP of 33 meters = Rs. 33.\nProfit = CP of 11 meters = Rs. 11.\nProfit % = (11 / 33) × 100 = 1/3 × 100 = 33 1/3% (33.33%).',
    exp_bn: 'ধরি ১ মিটার কাপড়ের ক্রয়মূল্য ১ টাকা। লাভ = ১১ টাকা, ক্রয়মূল্য = ৩৩ টাকা। শতকরা লাভ = (১১/৩৩) × ১০০ = ৩৩ ১/৩%।',
    fact: 'When profit is given as CP of x articles on selling y articles: Profit% = (x/y) × 100.',
    tip: '11/33 = 1/3 = 33.33%.'
  },
  {
    num: 65, subject_id: 'sub-arith',
    text: 'A car covers a distance of 180 km in 4 hours. If its speed is increased by 15 km/h, how much time will it take to cover the same distance?',
    text_bn: 'একটি গাড়ি ৪ ঘণ্টায় ১৮০ কিমি দূরত্ব অতিক্রম করে। যদি গাড়ির গতিবেগ ঘণ্টায় ১৫ কিমি বৃদ্ধি করা হয়, তবে ওই একই দূরত্ব যেতে কত সময় লাগবে?',
    a: '3 hours', a_bn: '৩ ঘণ্টা',
    b: '3.5 hours', b_bn: '৩.৫ ঘণ্টা',
    c: '2.5 hours', c_bn: '২.৫ ঘণ্টা',
    d: '2 hours', d_bn: '২ ঘণ্টা',
    ans: 'A',
    exp: 'Original speed = 180 km / 4 h = 45 km/h.\nNew increased speed = 45 + 15 = 60 km/h.\nNew time = 180 km / 60 km/h = 3 hours.',
    exp_bn: 'প্রাথমিক গতিবেগ = ১৮০/৪ = ৪৫ কিমি/ঘণ্টা। নতুন গতিবেগ = ৪৫ + ১৫ = ৬০ কিমি/ঘণ্টা। সময় লাগবে = ১৮০/৬০ = ৩ ঘণ্টা।',
    fact: 'Time saved = 4 hours - 3 hours = 1 hour.',
    tip: '180 / 60 = 3 hours.'
  },
  {
    num: 66, subject_id: 'sub-arith',
    text: 'What least number must be added to 1056 so that the sum is completely divisible by 23?',
    text_bn: '১০৫৬-এর সাথে কোন ক্ষুদ্রতম সংখ্যা যোগ করলে যোগফলটি ২৩ দ্বারা সম্পূর্ণরূপে বিভাজ্য হবে?',
    a: '2', a_bn: '২',
    b: '3', b_bn: '৩',
    c: '18', c_bn: '১৮',
    d: '21', d_bn: '২১',
    ans: 'A',
    exp: 'Divide 1056 by 23: 1056 = 23 × 45 + 21 (Remainder = 21).\nRequired number to add = Divisor - Remainder = 23 - 21 = 2.\n1056 + 2 = 1058, which is exactly divisible by 23 (23 × 46 = 1058).',
    exp_bn: '১০৫৬ কে ২৩ দিয়ে ভাগ করলে ভাগশেষ থাকে ২১। অতএব যোগ করতে হবে = ২৩ - ২১ = ২ (১০৫৮ = ২৩ × ৪৬)।',
    fact: 'To subtract, take remainder (21); to add, take (divisor - remainder) = 2.',
    tip: '1058 is divisible by 23.'
  },
  {
    num: 67, subject_id: 'sub-arith',
    text: 'The salary of an employee is first increased by 20% and then decreased by 20%. What is the net percentage change in his salary?',
    text_bn: 'একজন কর্মচারীর বেতন প্রথমে ২০% বৃদ্ধি পায় এবং পরে ২০% হ্রাস পায়। তার বেতনের নিট শতকরা পরিবর্তন কত?',
    a: '4% decrease', a_bn: '৪% হ্রাস (4% decrease)',
    b: 'No change (0%)', b_bn: 'কোনো পরিবর্তন নেই',
    c: '2% decrease', c_bn: '২% হ্রাস',
    d: '4% increase', d_bn: '৪% বৃদ্ধি',
    ans: 'A',
    exp: 'Successive percentage change formula = x + y + (xy/100)\n= +20 - 20 - (20 × 20)/100 = 0 - 4 = -4% (4% decrease).',
    exp_bn: 'বেতন ১০০ ধরলে: ১০০ -> ১২০ -> ১২০-এর ২০% কমে ৯৬ টাকা। অর্থাৎ ৪% হ্রাস পায়। সূত্র: x^2 / 100 = 400/100 = 4% হ্রাস।',
    fact: 'When an amount is increased by x% and then decreased by x%, there is ALWAYS a loss of (x^2 / 100)%.',
    tip: 'Direct rule: (20^2)/100 = 4% loss always.'
  },
  {
    num: 68, subject_id: 'sub-arith',
    text: 'If the cost of 15 identical pens is Rs. 195, what is the cost of 25 such pens?',
    text_bn: 'যদি ১৫টি কলমের মূল্য ১৯৫ টাকা হয়, তবে একই ধরনের ২৫টি কলমের মূল্য কত হবে?',
    a: 'Rs. 325', a_bn: '৩২৫ টাকা',
    b: 'Rs. 300', b_bn: '৩০০ টাকা',
    c: 'Rs. 350', c_bn: '৩৫০ টাকা',
    d: 'Rs. 280', d_bn: '২৮০ টাকা',
    ans: 'A',
    exp: 'Cost of 1 pen = Rs. 195 / 15 = Rs. 13.\nCost of 25 pens = 25 × 13 = Rs. 325.',
    exp_bn: '১টি কলমের দাম = ১৯৫ / ১৫ = ১৩ টাকা। ২৫টি কলমের দাম = ২৫ × ১৩ = ৩২৫ টাকা।',
    fact: 'Direct variation: 195 × (25 / 15) = 195 × (5 / 3) = 65 × 5 = Rs. 325.',
    tip: 'Unitary method: 13 × 25 = 325.'
  },
  {
    num: 69, subject_id: 'sub-arith',
    text: 'Find the Simple Interest on Rs. 5,000 for 3 years at 8% per annum.',
    text_bn: 'বার্ষিক ৮% সরল সুদে ৫,০০০ টাকার ৩ বছরের সুদ কত?',
    a: 'Rs. 1,200', a_bn: '১,২০০ টাকা',
    b: 'Rs. 1,000', b_bn: '১,০০০ টাকা',
    c: 'Rs. 1,500', c_bn: '১,৫০০ টাকা',
    d: 'Rs. 800', d_bn: '৮০০ টাকা',
    ans: 'A',
    exp: 'Simple Interest = (P × R × T) / 100 = (5000 × 8 × 3) / 100 = 50 × 24 = Rs. 1,200.',
    exp_bn: 'সরল সুদ = (P × R × T) / ১০০ = (৫০০০ × ৮ × ৩) / ১০০ = ১,২০০ টাকা।',
    fact: 'Total amount after 3 years = 5000 + 1200 = Rs. 6200.',
    tip: '8% of 5000 = 400 per year; 400 × 3 = 1200.'
  },
  {
    num: 70, subject_id: 'sub-arith',
    text: 'A tap can fill an empty cistern in 8 hours and a waste pipe can empty it in 12 hours. If both are opened together, in how many hours will the cistern be completely filled?',
    text_bn: 'একটি নল দ্বারা একটি খালি চৌবাচ্চা ৮ ঘণ্টায় পূর্ণ হয় এবং একটি নির্গম নল দ্বারা তা ১২ ঘণ্টায় খালি হয়। দুটি নল একসাথে খুলে দিলে চৌবাচ্চাটি পূর্ণ হতে কত সময় লাগবে?',
    a: '24 hours', a_bn: '২৪ ঘণ্টা',
    b: '20 hours', b_bn: '২০ ঘণ্টা',
    c: '16 hours', c_bn: '১৬ ঘণ্টা',
    d: '30 hours', d_bn: '৩০ ঘণ্টা',
    ans: 'A',
    exp: 'Net rate per hour = 1/8 - 1/12 = (3 - 2)/24 = 1/24.\nTime taken to fill = 24 hours.',
    exp_bn: '১ ঘণ্টায় পূর্ণ হয় = ১/৮ - ১/১২ = ১/২৪ অংশ। অতএব সম্পূর্ণ পূর্ণ হতে সময় লাগবে ২৪ ঘণ্টা।',
    fact: 'Formula: (A × B) / (B - A) = (8 × 12) / (12 - 8) = 96 / 4 = 24 hours.',
    tip: 'LCM of 8 and 12 is 24 units. Inflow = 3 units/h, Outflow = 2 units/h. Net = 1 unit/h. Time = 24/1 = 24 h.'
  },
  {
    num: 71, subject_id: 'sub-arith',
    text: 'A sum of Rs. 1,200 is divided among A, B, and C in the ratio 2 : 3 : 5. What is the share of B?',
    text_bn: '১,২০০ টাকা A, B ও C-এর মধ্যে ২ : ৩ : ৫ অনুপাতে ভাগ করে দিলে B কত টাকা পাবে?',
    a: 'Rs. 360', a_bn: '৩৬০ টাকা',
    b: 'Rs. 240', b_bn: '২৪০ টাকা',
    c: 'Rs. 600', c_bn: '৬০০ টাকা',
    d: 'Rs. 480', d_bn: '৪৮০ টাকা',
    ans: 'A',
    exp: 'Total ratio parts = 2 + 3 + 5 = 10 parts.\nValue of 1 part = 1200 / 10 = Rs. 120.\nShare of B (3 parts) = 3 × 120 = Rs. 360.',
    exp_bn: 'মোট অনুপাত = ২ + ৩ + ৫ = ১০। ১ ভাগের মান = ১২০০ / ১০ = ১২০ টাকা। B-এর প্রাপ্য = ৩ × ১২০ = ৩৬০ টাকা।',
    fact: 'Shares: A = Rs. 240, B = Rs. 360, C = Rs. 600.',
    tip: 'B\'s fraction = 3/10; 1200 × 3/10 = 360.'
  },
  {
    num: 72, subject_id: 'sub-arith',
    text: 'The difference between the length and breadth of a rectangle is 6 meters and its perimeter is 64 meters. What is the area of the rectangle?',
    text_bn: 'একটি আয়তক্ষেত্রের দৈর্ঘ্য ও প্রস্থের পার্থক্য ৬ মিটার এবং পরিসীমা ৬৪ মিটার। আয়তক্ষেত্রটির ক্ষেত্রফল কত?',
    a: '247 sq m', a_bn: '২৪৭ বর্গমিটার',
    b: '256 sq m', b_bn: '২৫৬ বর্গমিটার',
    c: '235 sq m', c_bn: '২৩৫ বর্গমিটার',
    d: '260 sq m', d_bn: '২৬০ বর্গমিটার',
    ans: 'A',
    exp: 'Perimeter 2(L + B) = 64 => L + B = 32.\nGiven L - B = 6.\nAdding equations: 2L = 38 => L = 19 m, B = 32 - 19 = 13 m.\nArea = L × B = 19 × 13 = 247 sq meters.',
    exp_bn: 'দৈর্ঘ্য + প্রস্থ = ৩২ এবং দৈর্ঘ্য - প্রস্থ = ৬। দৈর্ঘ্য = ১৯ মি, প্রস্থ = ১৩ মি। ক্ষেত্রফল = ১৯ × ১৩ = ২৪৭ বর্গমিটার।',
    fact: 'Algebraic check: Area = ((L+B)^2 - (L-B)^2) / 4 = (1024 - 36) / 4 = 988 / 4 = 247.',
    tip: '19 × 13 = (16+3)(16-3) = 256 - 9 = 247.'
  },
  {
    num: 73, subject_id: 'sub-arith',
    text: 'In an examination, 35% of candidates failed in Mathematics and 25% failed in English. If 15% failed in both subjects, what percentage of candidates passed in both subjects?',
    text_bn: 'একটি পরীক্ষায় ৩৫% পরীক্ষার্থী গণিতে এবং ২৫% ইংরেজিতে ফেল করে। যদি ১৫% উভয় বিষয়ে ফেল করে, তবে উভয় বিষয়ে শতকরা কতজন পাস করেছে?',
    a: '55%', a_bn: '৫৫%',
    b: '45%', b_bn: '৪৫%',
    c: '60%', c_bn: '৬০%',
    d: '50%', d_bn: '৫০%',
    ans: 'A',
    exp: 'Total failed candidates = %Failed in Math + %Failed in English - %Failed in Both\n= 35% + 25% - 15% = 45%.\nPassed in both subjects = 100% - 45% = 55%.',
    exp_bn: 'মোট ফেল = ৩৫ + ২৫ - ১৫ = ৪৫%। উভয় বিষয়ে পাস = ১০০ - ৪৫ = ৫৫%।',
    fact: 'Venn Diagram principle: n(A ∪ B) = n(A) + n(B) - n(A ∩ B).',
    tip: '100 - (35 + 25 - 15) = 55%.'
  },
  {
    num: 74, subject_id: 'sub-arith',
    text: 'A train travelling at a uniform speed of 72 km/h crosses a 200-meter long platform in 22 seconds. What is the length of the train?',
    text_bn: '৭২ কিমি/ঘণ্টা গতিবেগে ধাবমান একটি ট্রেন ২২ সেকেন্ডে ২০০ মিটার দীর্ঘ একটি প্ল্যাটফর্ম অতিক্রম করে। ট্রেনটির দৈর্ঘ্য কত?',
    a: '240 meters', a_bn: '২৪০ মিটার',
    b: '220 meters', b_bn: '২২০ মিটার',
    c: '250 meters', c_bn: '২৫০ মিটার',
    d: '260 meters', d_bn: '২৬০ মিটার',
    ans: 'A',
    exp: 'Speed in m/s = 72 × (5/18) = 20 m/s.\nTotal distance covered in 22 seconds = Speed × Time = 20 × 22 = 440 meters.\nLength of Train = Total distance - Length of Platform = 440 - 200 = 240 meters.',
    exp_bn: 'গতিবেগ = ৭২ × ৫/১৮ = ২০ মি/সে। মোট অতিক্রান্ত দূরত্ব = ২০ × ২২ = ৪৪০ মিটার। ট্রেনের দৈর্ঘ্য = ৪৪০ - ২০০ = ২৪০ মিটার।',
    fact: 'Distance = Length of train + Length of platform.',
    tip: '440 - 200 = 240 m.'
  },
  {
    num: 75, subject_id: 'sub-arith',
    text: 'The average score of a batsman in 8 innings is 45 runs. In the 9th inning, he scores 90 runs. What is his new batting average?',
    text_bn: 'একজন ব্যাটসম্যানের ৮টি ইনিংসের গড় রান ৪৫। ৯ম ইনিংসে তিনি ৯০ রান করেন। তার নতুন ব্যাটিং গড় কত?',
    a: '50 runs', a_bn: '৫০ রান',
    b: '48 runs', b_bn: '৪৮ রান',
    c: '52 runs', c_bn: '৫২ রান',
    d: '55 runs', d_bn: '৫৫ রান',
    ans: 'A',
    exp: 'Total runs in 8 innings = 8 × 45 = 360 runs.\nTotal runs in 9 innings = 360 + 90 = 450 runs.\nNew Average = 450 / 9 = 50 runs.',
    exp_bn: '৮ ইনিংসের মোট রান = ৮ × ৪৫ = ৩৬০। ৯ ইনিংসের মোট রান = ৩৬০ + ৯০ = ৪৫০। নতুন গড় = ৪৫০ / ৯ = ৫০ রান।',
    fact: 'Shortcut: Extra runs above previous average = 90 - 45 = 45 runs. Increase per inning = 45 / 9 = 5 runs. New average = 45 + 5 = 50.',
    tip: '45 + (90 - 45)/9 = 45 + 5 = 50.'
  },
  {
    num: 76, subject_id: 'sub-arith',
    text: 'A boat travels 24 km downstream in 2 hours and 16 km upstream in 4 hours. What is the speed of the river stream?',
    text_bn: 'একটি নৌকা স্রোতের অনুকূলে ২৪ কিমি যায় ২ ঘণ্টায় এবং স্রোতের প্রতিকূলে ১৬ কিমি যায় ৪ ঘণ্টায়। নদীর স্রোতের বেগ কত?',
    a: '4 km/h', a_bn: '৪ কিমি/ঘণ্টা',
    b: '8 km/h', b_bn: '৮ কিমি/ঘণ্টা',
    c: '3 km/h', c_bn: '৩ কিমি/ঘণ্টা',
    d: '5 km/h', d_bn: '৫ কিমি/ঘণ্টা',
    ans: 'A',
    exp: 'Downstream speed (u) = 24 / 2 = 12 km/h.\nUpstream speed (v) = 16 / 4 = 4 km/h.\nSpeed of Stream = (u - v) / 2 = (12 - 4) / 2 = 8 / 2 = 4 km/h.',
    exp_bn: 'অনুকূলে গতিবেগ = ১২ কিমি/ঘণ্টা, প্রতিকূলে গতিবেগ = ৪ কিমি/ঘণ্টা। স্রোতের বেগ = (১২ - ৪) / ২ = ৪ কিমি/ঘণ্টা।',
    fact: 'Speed of boat in still water = (12 + 4) / 2 = 8 km/h.',
    tip: 'Stream speed = (Downstream - Upstream) / 2.'
  },
  {
    num: 77, subject_id: 'sub-arith',
    text: 'Evaluate the arithmetic expression: (0.2 × 0.2 + 0.04) ÷ 0.2',
    text_bn: 'মান নির্ণয় করুন: (০.২ × ০.২ + ০.০৪) ÷ ০.২',
    a: '0.4', a_bn: '০.৪',
    b: '0.2', b_bn: '০.২',
    c: '0.04', c_bn: '০.০৪',
    d: '0.8', d_bn: '০.৮',
    ans: 'A',
    exp: 'Numerator = 0.04 + 0.04 = 0.08.\n0.08 ÷ 0.2 = 0.8 / 2 = 0.4.',
    exp_bn: '(০.০৪ + ০.০৪) ÷ ০.২ = ০.০৮ ÷ ০.২ = ০.৪।',
    fact: '0.08 / 0.2 = 8/20 = 2/5 = 0.4.',
    tip: 'Align decimal places: 0.08 / 0.20 = 8/20 = 0.4.'
  },
  {
    num: 78, subject_id: 'sub-arith',
    text: 'If 6 men and 8 boys can finish a job in 10 days, in how many days can 15 men and 20 boys finish the exact same job?',
    text_bn: 'যদি ৬ জন পুরুষ ও ৮ জন বালক একটি কাজ ১০ দিনে করতে পারে, তবে ১৫ জন পুরুষ ও ২০ জন বালক ওই কাজটি কত দিনে করতে পারবে?',
    a: '4 days', a_bn: '৪ দিন',
    b: '5 days', b_bn: '৫ দিন',
    c: '6 days', c_bn: '৬ দিন',
    d: '8 days', d_bn: '৮ দিন',
    ans: 'A',
    exp: 'Notice the proportionality: 15 men + 20 boys = 2.5 × (6 men + 8 boys).\nSince the workforce is increased by 2.5 times (5/2), the time required will be reduced by 2.5 times.\nTime = 10 days ÷ 2.5 = 4 days.',
    exp_bn: '১৫ জন পুরুষ + ২০ জন বালক হলো (৬ জন পুরুষ + ৮ জন বালক)-এর ২.৫ গুণ। সুতরাং সময় লাগবে = ১০ / ২.৫ = ৪ দিন।',
    fact: 'Workforce ratio = 15/6 = 20/8 = 2.5.',
    tip: '10 / (2.5) = 4 days.'
  },
  {
    num: 79, subject_id: 'sub-arith',
    text: 'A merchant marks his goods 20% above the cost price and allows a discount of 10% on the marked price. What is his net gain percentage?',
    text_bn: 'একজন ব্যবসায়ী তার পণ্যের ওপর ক্রয়মূল্যের চেয়ে ২০% বেশি ধার্যমূল্য নির্ধারণ করেন এবং বিক্রির সময় ১০% ছাড় দেন। তার শতকরা লাভের হার কত?',
    a: '8%', a_bn: '৮%',
    b: '10%', b_bn: '১০%',
    c: '12%', c_bn: '১২%',
    d: '5%', d_bn: '৫%',
    ans: 'A',
    exp: 'Let CP = Rs. 100. Marked Price (MP) = Rs. 120.\nDiscount = 10% of 120 = Rs. 12.\nSelling Price (SP) = 120 - 12 = Rs. 108.\nProfit = 108 - 100 = 8%.',
    exp_bn: 'ক্রয়মূল্য ১০০ হলে ধার্যমূল্য ১২০ টাকা। ১০% ছাড়ে বিক্রয়মূল্য = ১২০ - ১২ = ১০৮ টাকা। লাভ = ৮%।',
    fact: 'Formula: Profit% = Markup% - Discount% - (Markup × Discount)/100 = 20 - 10 - 2 = 8%.',
    tip: '100 -> 120 -> 108 => 8% profit.'
  },
  {
    num: 80, subject_id: 'sub-arith',
    text: 'The diagonal of a square is 10 cm. What is the area of the square?',
    text_bn: 'একটি বর্গক্ষেত্রের কর্ণের দৈর্ঘ্য ১০ সেমি। বর্গক্ষেত্রটির ক্ষেত্রফল কত?',
    a: '50 sq cm', a_bn: '৫০ বর্গ সেমি',
    b: '100 sq cm', b_bn: '১০০ বর্গ সেমি',
    c: '25 sq cm', c_bn: '২৫ বর্গ সেমি',
    d: '75 sq cm', d_bn: '৭৫ বর্গ সেমি',
    ans: 'A',
    exp: 'Area of a square = (Diagonal)^2 / 2 = (10)^2 / 2 = 100 / 2 = 50 sq cm.',
    exp_bn: 'বর্গক্ষেত্রের ক্ষেত্রফল = (কর্ণ)^২ / ২ = (১০)^২ / ২ = ১০০ / ২ = ৫০ বর্গ সেমি।',
    fact: 'Side of square a = 10 / √2 = 5√2 cm; Area = a^2 = (5√2)^2 = 50 sq cm.',
    tip: 'Direct formula: Area = d^2 / 2.'
  },
  {
    num: 81, subject_id: 'sub-arith',
    text: 'Find the Least Common Multiple (LCM / ল.সা.গু.) of 24, 36, and 40.',
    text_bn: '২৪, ৩৬ এবং ৪০-এর লঘিষ্ঠ সাধারণ গুণিতক (ল.সা.গু. / LCM) কত?',
    a: '360', a_bn: '৩৬০',
    b: '240', b_bn: '২৪০',
    c: '180', c_bn: '১৮০',
    d: '480', d_bn: '৪৮০',
    ans: 'A',
    exp: '24 = 2^3 × 3\n36 = 2^2 × 3^2\n40 = 2^3 × 5\nLCM = 2^3 × 3^2 × 5 = 8 × 9 × 5 = 360.',
    exp_bn: '২৪, ৩৬ ও ৪০-এর মৌলিক উৎপাদকে বিশ্লেষণ করলে পাই ২^৩ × ৩^২ × ৫ = ৩৬০।',
    fact: '360 is divisible by 24 (15), 36 (10), and 40 (9).',
    tip: 'Take highest powers of all prime factors.'
  },
  {
    num: 82, subject_id: 'sub-arith',
    text: 'If x : y = 3 : 5, find the value of (5x + 3y) : (7x - 2y).',
    text_bn: 'যদি x : y = ৩ : ৫ হয়, তবে (৫x + ৩y) : (৭x - ২y)-এর মান কত?',
    a: '30 : 11', a_bn: '৩০ : ১১',
    b: '25 : 11', b_bn: '২৫ : ১১',
    c: '30 : 13', c_bn: '৩০ : ১৩',
    d: '28 : 11', d_bn: '২৮ : ১১',
    ans: 'A',
    exp: 'Substitute x = 3 and y = 5:\nNumerator = 5(3) + 3(5) = 15 + 15 = 30.\nDenominator = 7(3) - 2(5) = 21 - 10 = 11.\nRatio = 30 : 11.',
    exp_bn: 'x = ৩ এবং y = ৫ বসালে: (৫×৩ + ৩×৫) : (৭×৩ - ২×৫) = (১৫ + ১৫) : (২১ - ১০) = ৩০ : ১১।',
    fact: 'Homogeneous expression allows direct substitution.',
    tip: '30 / 11.'
  },
  {
    num: 83, subject_id: 'sub-arith',
    text: 'Three positive numbers are in the ratio 1 : 2 : 3 and the sum of their squares is 504. What are the numbers?',
    text_bn: 'তিনটি ধনাত্মক সংখ্যার অনুপাত ১ : ২ : ৩ এবং তাদের বর্গের সমষ্টি ৫০৪। সংখ্যা তিনটি কী কী?',
    a: '6, 12, 18', a_bn: '৬, ১২, ১৮',
    b: '4, 8, 12', b_bn: '৪, ৮, ১২',
    c: '5, 10, 15', c_bn: '৫, ১০, ১৫',
    d: '7, 14, 21', d_bn: '৭, ১৪, ২১',
    ans: 'A',
    exp: 'Let numbers be x, 2x, 3x.\n(x)^2 + (2x)^2 + (3x)^2 = 504 => x^2 + 4x^2 + 9x^2 = 504 => 14x^2 = 504 => x^2 = 36 => x = 6.\nNumbers are 6, 12, 18.',
    exp_bn: 'x^২ + ৪x^২ + ৯x^২ = ৫০৪ => ১৪x^২ = ৫০৪ => x^২ = ৩৬ => x = ৬। সংখ্যা তিনটি হলো ৬, ১২, ১৮।',
    fact: '6^2 + 12^2 + 18^2 = 36 + 144 + 324 = 504.',
    tip: 'Check squares: 36 + 144 + 324 = 504.'
  },
  {
    num: 84, subject_id: 'sub-arith',
    text: 'A sum of money placed at compound interest amounts to Rs. 2,420 in 2 years and to Rs. 2,662 in 3 years. What is the annual rate of interest?',
    text_bn: 'কোনো মূলধন চক্রবৃদ্ধি সুদে ২ বছরে ২,৪২০ টাকা এবং ৩ বছরে ২,৬৬২ টাকা হয়। বার্ষিক সুদের হার কত?',
    a: '10% per annum', a_bn: '১০% বার্ষিক',
    b: '8% per annum', b_bn: '৮% বার্ষিক',
    c: '12% per annum', c_bn: '১২% বার্ষিক',
    d: '5% per annum', d_bn: '৫% বার্ষিক',
    ans: 'A',
    exp: 'Interest for the 3rd year = 2662 - 2420 = Rs. 242.\nRate R = (Interest / Previous Amount) × 100 = (242 / 2420) × 100 = 10% per annum.',
    exp_bn: '১ বছরের সুদ = ২৬৬২ - ২৪২০ = ২৪২ টাকা। সুদের হার = (২৪২ / ২৪২০) × ১০০ = ১০%।',
    fact: 'Consecutive year compound interest difference directly gives the 1-year rate.',
    tip: '242 / 2420 = 1/10 = 10%.'
  },
  {
    num: 85, subject_id: 'sub-arith',
    text: 'A solid right circular cylinder has a radius of 7 cm and a height of 10 cm. What is its curved surface area? (Take π = 22/7)',
    text_bn: 'একটি লম্ব বৃত্তাকার চোঙের ব্যাসার্ধ ৭ সেমি এবং উচ্চতা ১০ সেমি। এর বক্রতলের ক্ষেত্রফল কত? (π = ২২/৭ ধরুন)',
    a: '440 sq cm', a_bn: '৪৪০ বর্গ সেমি',
    b: '220 sq cm', b_bn: '২২০ বর্গ সেমি',
    c: '350 sq cm', c_bn: '৩৫০ বর্গ সেমি',
    d: '540 sq cm', d_bn: '৫৪০ বর্গ সেমি',
    ans: 'A',
    exp: 'Curved Surface Area of Cylinder = 2πrh = 2 × (22/7) × 7 × 10 = 2 × 22 × 10 = 440 sq cm.',
    exp_bn: 'চোঙের বক্রতলের ক্ষেত্রফল = ২πrh = ২ × (২২/৭) × ৭ × ১০ = ৪৪০ বর্গ সেমি।',
    fact: 'Total Surface Area = 2πr(r + h) = 2 × 22/7 × 7 × (7 + 10) = 44 × 17 = 748 sq cm.',
    tip: '2 × 22 × 10 = 440.'
  },
  {
    num: 86, subject_id: 'sub-arith',
    text: 'If a : b = 5 : 7 and b : c = 6 : 11, find the ratio a : c.',
    text_bn: 'যদি a : b = ৫ : ৭ এবং b : c = ৬ : ১১ হয়, তবে a : c-এর মান কত?',
    a: '30 : 77', a_bn: '৩০ : ৭৭',
    b: '35 : 66', b_bn: '৩৫ : ৬৬',
    c: '30 : 66', c_bn: '৩০ : ৬৬',
    d: '25 : 77', d_bn: '২৫ : ৭৭',
    ans: 'A',
    exp: 'a/c = (a/b) × (b/c) = (5/7) × (6/11) = 30/77 => a : c = 30 : 77.',
    exp_bn: 'a/c = (a/b) × (b/c) = (৫/৭) × (৬/১১) = ৩০/৭৭। অতএব a : c = ৩০ : ৭৭।',
    fact: 'Compound ratio multiplication: (5×6) : (7×11) = 30 : 77.',
    tip: 'Multiply numerators and denominators directly.'
  },
  {
    num: 87, subject_id: 'sub-arith',
    text: 'What is the sum of 15% of 250 and 25% of 150?',
    text_bn: '২৫০-এর ১৫% এবং ১৫০-এর ২৫%-এর যোগফল কত?',
    a: '75', a_bn: '৭৫',
    b: '80', b_bn: '৮০',
    c: '70', c_bn: '৭০',
    d: '85', d_bn: '৮৫',
    ans: 'A',
    exp: '15% of 250 = (15 × 250)/100 = 37.5\n25% of 150 = (25 × 150)/100 = 37.5\nSum = 37.5 + 37.5 = 75.',
    exp_bn: '২৫০-এর ১৫% = ৩৭.৫ এবং ১৫০-এর ২৫% = ৩৭.৫। যোগফল = ৩৭.৫ + ৩৭.৫ = ৭৫।',
    fact: 'Symmetry property: x% of y = y% of x. 15% of 250 = 25% of 150.',
    tip: '2 × 37.5 = 75.'
  },
  {
    num: 88, subject_id: 'sub-arith',
    text: 'A person walks at a speed of 5 km/h for 3 hours and then jogs at 9 km/h for 2 hours. What is his overall average speed for the entire journey?',
    text_bn: 'এক ব্যক্তি ঘণ্টায় ৫ কিমি গতিবেগে ৩ ঘণ্টা হাঁটেন এবং পরবর্তী ২ ঘণ্টা ঘণ্টায় ৯ কিমি গতিবেগে দৌড়ান। পুরো যাত্রায় তার গড় গতিবেগ কত?',
    a: '6.6 km/h', a_bn: '৬.৬ কিমি/ঘণ্টা',
    b: '7.0 km/h', b_bn: '৭.০ কিমি/ঘণ্টা',
    c: '6.2 km/h', c_bn: '৬.২ কিমি/ঘণ্টা',
    d: '7.2 km/h', d_bn: '৭.২ কিমি/ঘণ্টা',
    ans: 'A',
    exp: 'Total Distance = (5 × 3) + (9 × 2) = 15 + 18 = 33 km.\nTotal Time = 3 + 2 = 5 hours.\nAverage Speed = Total Distance / Total Time = 33 / 5 = 6.6 km/h.',
    exp_bn: 'মোট দূরত্ব = (৫×৩) + (৯×২) = ১৫ + ১৮ = ৩৩ কিমি। মোট সময় = ৩ + ২ = ৫ ঘণ্টা। গড় গতিবেগ = ৩৩ / ৫ = ৬.৬ কিমি/ঘণ্টা।',
    fact: 'Average speed is ALWAYS total distance divided by total time.',
    tip: '33 / 5 = 6.6 km/h.'
  },
  {
    num: 89, subject_id: 'sub-arith',
    text: 'Two numbers are in the ratio 7 : 9. If 6 is subtracted from each of them, the ratio becomes 5 : 7. What are the original numbers?',
    text_bn: 'দুটি সংখ্যার অনুপাত ৭ : ৯। প্রতিটি সংখ্যা থেকে ৬ বিয়োগ করলে অনুপাত হয় ৫ : ৭। মূল সংখ্যা দুটি কী কী?',
    a: '21 and 27', a_bn: '২১ এবং ২৭',
    b: '14 and 18', b_bn: '১৪ এবং ১৮',
    c: '28 and 36', c_bn: '২৮ এবং ৩৬',
    d: '35 and 45', d_bn: '৩৫ এবং ৪৫',
    ans: 'A',
    exp: 'Let numbers be 7x and 9x.\n(7x - 6) / (9x - 6) = 5 / 7 => 49x - 42 = 45x - 30 => 4x = 12 => x = 3.\nNumbers are: 7(3) = 21 and 9(3) = 27.',
    exp_bn: '(৭x - ৬)/(৯x - ৬) = ৫/৭ => ৪৯x - ৪২ = ৪৫x - ৩০ => ৪x = ১২ => x = ৩। সংখ্যা দুটি হলো ২১ এবং ২৭।',
    fact: 'Ratio unit change is 2 units = 6 => 1 unit = 3. Numbers = 7×3 = 21, 9×3 = 27.',
    tip: 'Check: 21 - 6 = 15; 27 - 6 = 21. 15:21 = 5:7.'
  },
  {
    num: 90, subject_id: 'sub-arith',
    text: 'The diameter of a circle is 28 cm. What is the area of the circle? (Take π = 22/7)',
    text_bn: 'একটি বৃত্তের ব্যাস ২৮ সেমি। বৃত্তটির ক্ষেত্রফল কত? (π = ২২/৭)',
    a: '616 sq cm', a_bn: '৬১৬ বর্গ সেমি',
    b: '308 sq cm', b_bn: '৩০৮ বর্গ সেমি',
    c: '628 sq cm', c_bn: '৬২৮ বর্গ সেমি',
    d: '516 sq cm', d_bn: '৫১৬ বর্গ সেমি',
    ans: 'A',
    exp: 'Radius r = Diameter / 2 = 28 / 2 = 14 cm.\nArea of Circle = πr^2 = (22/7) × 14 × 14 = 22 × 2 × 14 = 44 × 14 = 616 sq cm.',
    exp_bn: 'ব্যাসার্ধ r = ২৮/২ = ১৪ সেমি। ক্ষেত্রফল = πr^২ = ২২/৭ × ১৪ × ১৪ = ৬১৬ বর্গ সেমি।',
    fact: 'Circumference = 2πr = 2 × 22/7 × 14 = 88 cm.',
    tip: 'Area for radius 7 is 154; for radius 14 (double), area is 154 × 4 = 616.'
  },
  {
    num: 91, subject_id: 'sub-arith',
    text: 'By selling an article for Rs. 140, a shopkeeper makes a profit of 16 2/3%. What is the cost price of the article?',
    text_bn: '১৪০ টাকায় একটি জিনিস বিক্রি করে এক দোকানদার ১৬ ২/৩% লাভ করেন। জিনিসটির ক্রয়মূল্য কত?',
    a: 'Rs. 120', a_bn: '১২০ টাকা',
    b: 'Rs. 125', b_bn: '১২৫ টাকা',
    c: 'Rs. 115', c_bn: '১১৫ টাকা',
    d: 'Rs. 130', d_bn: '১৩০ টাকা',
    ans: 'A',
    exp: '16 2/3% = 1/6 fraction.\nIf CP = 6 units, Profit = 1 unit => SP = 7 units.\n7 units = Rs. 140 => 1 unit = Rs. 20.\nCost Price (6 units) = 6 × 20 = Rs. 120.',
    exp_bn: '১৬ ২/৩% = ১/৬। ক্রয়মূল্য ৬ হলে বিক্রয়মূল্য ৭। ৭ একক = ১৪০ টাকা => ১ একক = ২০ টাকা। ক্রয়মূল্য = ৬ × ২০ = ১২০ টাকা।',
    fact: 'Fraction conversion: 16 2/3% = 50/300 = 1/6.',
    tip: '140 × (6/7) = 120.'
  },
  {
    num: 92, subject_id: 'sub-arith',
    text: 'If x + 1/x = 4, find the value of x^2 + 1/x^2.',
    text_bn: 'যদি x + ১/x = ৪ হয়, তবে x^২ + ১/x^২-এর মান কত?',
    a: '14', a_bn: '১৪',
    b: '16', b_bn: '১৬',
    c: '18', c_bn: '১৮',
    d: '12', d_bn: '১২',
    ans: 'A',
    exp: 'Squaring both sides: (x + 1/x)^2 = 4^2\nx^2 + 2 + 1/x^2 = 16 => x^2 + 1/x^2 = 16 - 2 = 14.',
    exp_bn: 'উভয়পক্ষকে বর্গ করে: x^২ + ২ + ১/x^২ = ১৬ => x^২ + ১/x^২ = ১৬ - ২ = ১৪।',
    fact: 'Formula: x^2 + 1/x^2 = k^2 - 2, where k = (x + 1/x).',
    tip: '4^2 - 2 = 14.'
  },
  {
    num: 93, subject_id: 'sub-arith',
    text: 'The interior angles of a triangle are in the ratio 2 : 3 : 5. What is the measure of the smallest angle in degrees?',
    text_bn: 'একটি ত্রিভুজের তিনটি কোণের অনুপাত ২ : ৩ : ৫। ক্ষুদ্রতম কোণটির পরিমাপ কত ডিগ্রি?',
    a: '36°', a_bn: '৩৬°',
    b: '45°', b_bn: '৪৫°',
    c: '30°', c_bn: '৩০°',
    d: '54°', d_bn: '৫৪°',
    ans: 'A',
    exp: 'Sum of angles in a triangle = 180°.\nTotal ratio parts = 2 + 3 + 5 = 10 parts.\nSmallest angle (2 parts) = 180° × (2 / 10) = 36°.',
    exp_bn: 'ত্রিভুজের তিন কোণের সমষ্টি ১৮০°। মোট অনুপাত = ১০। ক্ষুদ্রতম কোণ = ১৮০° × (২/১০) = ৩৬°।',
    fact: 'The three angles are 36°, 54°, and 90° (Right-angled triangle).',
    tip: '180 / 10 = 18°; 18° × 2 = 36°.'
  },
  {
    num: 94, subject_id: 'sub-arith',
    text: 'A bag contains 5 red balls, 4 blue balls, and 3 green balls. If one ball is drawn at random, what is the probability of drawing a blue ball?',
    text_bn: 'একটি থলিতে ৫টি লাল, ৪টি নীল এবং ৩টি সবুজ বল আছে। দৈবচয়নভাবে একটি বল তুললে বলটি নীল হওয়ার সম্ভাবনা কত?',
    a: '1/3', a_bn: '১/৩',
    b: '1/4', b_bn: '১/৪',
    c: '1/2', c_bn: '১/২',
    d: '5/12', d_bn: '৫/১২',
    ans: 'A',
    exp: 'Total balls = 5 + 4 + 3 = 12.\nFavorable outcomes (Blue balls) = 4.\nProbability = 4 / 12 = 1/3.',
    exp_bn: 'মোট বল = ৫ + ৪ + ৩ = ১২টি। নীল বল = ৪টি। সম্ভাবনা = ৪/১২ = ১/৩।',
    fact: 'Probability P(E) = Favorable outcomes / Total outcomes.',
    tip: '4/12 = 1/3.'
  },
  {
    num: 95, subject_id: 'sub-arith',
    text: 'A principal of Rs. 6,500 amounts to Rs. 8,450 in 5 years at simple interest. What is the annual interest rate per annum?',
    text_bn: 'বার্ষিক সরল সুদে ৬,৫০০ টাকা ৫ বছরে সুদে-আসলে ৮,৪৫০ টাকা হয়। বার্ষিক সুদের হার কত?',
    a: '6% per annum', a_bn: '৬% বার্ষিক',
    b: '5% per annum', b_bn: '৫% বার্ষিক',
    c: '7% per annum', c_bn: '৭% বার্ষিক',
    d: '8% per annum', d_bn: '৮% বার্ষিক',
    ans: 'A',
    exp: 'Simple Interest = 8450 - 6500 = Rs. 1,950.\nRate R = (SI × 100) / (P × T) = (1950 × 100) / (6500 × 5) = 195000 / 32500 = 6% per annum.',
    exp_bn: 'সুদ = ৮৪৫০ - ৬৫০০ = ১,৯৫০ টাকা। সুদের হার = (১৯৫০ × ১০০)/(৬৫০০ × ৫) = ৬%।',
    fact: 'Interest per year = 1950 / 5 = Rs. 390. Rate = (390 / 6500) × 100 = 6%.',
    tip: '390 / 65 = 6%.'
  },
  {
    num: 96, subject_id: 'sub-arith',
    text: 'What is the exact square root of the number 7056 (√7056)?',
    text_bn: '৭০৫৬ সংখ্যাটির বর্গমূল কত (√৭০৫৬)?',
    a: '84', a_bn: '৮৪',
    b: '86', b_bn: '৮৬',
    c: '74', c_bn: '৭৪',
    d: '76', d_bn: '৭৬',
    ans: 'A',
    exp: '84 × 84 = 7056. Since 80^2 = 6400 and 90^2 = 8100, and last digit is 6 (4^2 or 6^2), 84^2 = 7056.',
    exp_bn: '৮৪ × ৮৪ = ৭০৫৬। অতএব √৭০৫৬ = ৮৪।',
    fact: 'Prime factorization: 7056 = 2^4 × 3^2 × 7^2 => √7056 = 2^2 × 3 × 7 = 4 × 21 = 84.',
    tip: '84 × 84 = (80+4)^2 = 6400 + 640 + 16 = 7056.'
  },
  {
    num: 97, subject_id: 'sub-arith',
    text: 'In how many different ways can the 6 distinct letters of the word "BENGAL" be arranged?',
    text_bn: '"BENGAL" শব্দটির ৬টি বর্ণকে কত বিভিন্ন উপায়ে সাজানো যেতে পারে?',
    a: '720 ways', a_bn: '৭২০ উপায়ে',
    b: '120 ways', b_bn: '১২০ উপায়ে',
    c: '360 ways', c_bn: '৩৬০ উপায়ে',
    d: '5040 ways', d_bn: '৫০৪০ উপায়ে',
    ans: 'A',
    exp: 'The word "BENGAL" contains 6 distinct letters (B, E, N, G, A, L) with no repetitions.\nTotal arrangements = 6! = 6 × 5 × 4 × 3 × 2 × 1 = 720.',
    exp_bn: '"BENGAL" শব্দে ৬টি ভিন্ন অক্ষর রয়েছে। মোট বিন্যাস সংখ্যা = ৬! = ৬ × ৫ × ৪ × ৩ × ২ × ১ = ৭২০।',
    fact: 'Factorial values: 4! = 24, 5! = 120, 6! = 720, 7! = 5040.',
    tip: '6! = 720.'
  },
  {
    num: 98, subject_id: 'sub-arith',
    text: 'A rectangular park 30 meters long and 20 meters wide is surrounded on the outside by a pathway 2 meters wide. What is the area of the pathway in square meters?',
    text_bn: '৩০ মিটার দীর্ঘ এবং ২০ মিটার চওড়া একটি আয়তাকার পার্কের বাইরে চারদিকে ২ মিটার চওড়া একটি রাস্তা আছে। রাস্তাটির ক্ষেত্রফল কত বর্গমিটার?',
    a: '216 sq m', a_bn: '২১৬ বর্গমিটার',
    b: '200 sq m', b_bn: '২০০ বর্গমিটার',
    c: '240 sq m', c_bn: '২৪০ বর্গমিটার',
    d: '180 sq m', d_bn: '১৮০ বর্গমিটার',
    ans: 'A',
    exp: 'Inner area of park = 30 × 20 = 600 sq m.\nOuter length with path = 30 + (2 × 2) = 34 m.\nOuter width with path = 20 + (2 × 2) = 24 m.\nTotal outer area = 34 × 24 = 816 sq m.\nArea of path = Outer area - Inner area = 816 - 600 = 216 sq m.',
    exp_bn: 'পার্কের ভেতরের ক্ষেত্রফল = ৩০ × ২০ = ৬০০ বর্গমি। বাইরের দৈর্ঘ্য = ৩৪ মি, প্রস্থ = ২৪ মি। বাইরের ক্ষেত্রফল = ৩৪ × ২৪ = ৮১৬ বর্গমি। রাস্তার ক্ষেত্রফল = ৮১৬ - ৬০০ = ২১৬ বর্গমিটার।',
    fact: 'Formula: Area of outer path = 2w(L + B + 2w) = 2(2)(30 + 20 + 4) = 4 × 54 = 216 sq m.',
    tip: '4 × 54 = 216.'
  },
  {
    num: 99, subject_id: 'sub-arith',
    text: 'If 3^(x - y) = 27 and 3^(x + y) = 243, find the numerical value of x.',
    text_bn: 'যদি ৩^(x - y) = ২৭ এবং ৩^(x + y) = ২৪৩ হয়, তবে x-এর মান কত?',
    a: '4', a_bn: '৪',
    b: '3', b_bn: '৩',
    c: '5', c_bn: '৫',
    d: '2', d_bn: '২',
    ans: 'A',
    exp: '3^(x - y) = 27 = 3^3 => x - y = 3\n3^(x + y) = 243 = 3^5 => x + y = 5\nAdding both equations: 2x = 8 => x = 4.',
    exp_bn: '৩^(x - y) = ৩^৩ => x - y = ৩ এবং ৩^(x + y) = ৩^৫ => x + y = ৫। যোগ করলে ২x = ৮ => x = ৪।',
    fact: 'y = 1; x = 4.',
    tip: '(3 + 5)/2 = 4.'
  },
  {
    num: 100, subject_id: 'sub-arith',
    text: 'The average of 10 distinct numbers is 15. If each number is multiplied by 3, what will be the new average of the numbers?',
    text_bn: '১০টি সংখ্যার গড় ১৫। যদি প্রতিটি সংখ্যাকে ৩ দিয়ে গুণ করা হয়, তবে নতুন গড় কত হবে?',
    a: '45', a_bn: '৪৫',
    b: '30', b_bn: '৩০',
    c: '15', c_bn: '১৫',
    d: '50', d_bn: '৫০',
    ans: 'A',
    exp: 'Property of Average: If every observation is multiplied by a constant k, the new average also becomes k times the original average.\nNew Average = 15 × 3 = 45.',
    exp_bn: 'গড়ের নিয়ম অনুযায়ী প্রতিটি সংখ্যাকে যে ধ্রুবক দিয়ে গুণ করা হয়, গড়ও সেই অনুপাতে পরিবর্তিত হয়। নতুন গড় = ১৫ × ৩ = ৪৫।',
    fact: 'If every term is added, subtracted, multiplied, or divided by k, the average changes by the same operation.',
    tip: '15 × 3 = 45.'
  }
];

// Insert the 100 Food SI 2019 Questions
const insertTrans = db.transaction(() => {
  for (const q of ALL_100_FOOD_SI_2019) {
    const qId = `pyq-foodsi-2019-q${String(q.num).padStart(3, '0')}`;

    insertQuestionStmt.run({
      id: qId,
      question_text: q.text,
      question_text_bn: q.text_bn,
      option_a: q.a,
      option_b: q.b,
      option_c: q.c,
      option_d: q.d,
      option_a_bn: q.a_bn,
      option_b_bn: q.b_bn,
      option_c_bn: q.c_bn,
      option_d_bn: q.d_bn,
      correct_answer: q.ans,
      explanation: q.exp,
      explanation_bn: q.exp_bn,
      important_fact: q.fact,
      exam_tip: q.tip,
      exam_id: 'exam-food-si',
      subject_id: q.subject_id,
      difficulty: 'Medium'
    });

    insertMockQuestionStmt.run({
      id: `mq-mock-pyq-food-si-2019-${q.num}`,
      mock_id: 'mock-pyq-food-si-2019',
      question_id: qId,
      section_name: q.num <= 50 ? 'General Studies & Current Affairs' : 'Arithmetic & Numerical Ability',
      order_index: q.num,
      marks: 1.0,
      negative_marks: 0.33
    });

    insertPyqMetaStmt.run({
      id: `pyq-meta-${qId}`,
      question_id: qId,
      exam_id: 'exam-food-si',
      exam_year: 2019,
      exam_date: '2019-01-27',
      paper_name: 'WBPSC Food SI Official Question Paper (27 Jan 2019)',
      shift: 'Official Afternoon Shift (01:00 PM - 02:30 PM)',
      question_num: q.num,
      source_name: 'WBPSC Official Answer Key & Question Booklet (Advt. No. 26/2018)'
    });
  }
});

insertTrans();

console.log('🎉 Successfully seeded ALL 100 VERBATIM QUESTIONS for Food SI 2019 in exact 1:1 order!');
